pub mod http_nano_banana_2_edit_image;
pub mod http_nano_banana_2_text_to_image;
pub mod http_qwen_edit_2511_edit_image_angle;
pub mod http_seedream_5_edit_image;
pub mod http_seedream_5_text_to_image;
