// NB: Incrementally getting rid of build warnings...
#![forbid(unused_imports)]
#![forbid(unused_mut)]
#![forbid(unused_variables)]

use std::sync::Arc;

use actix_web::{web, HttpRequest, HttpResponse};
use chrono::{DateTime, Utc};
use log::error;

use datetimes::CHRONO_DATETIME_UNIX_EPOCH;
use enums::by_table::model_categories::model_type::ModelType;
use tokens::tokens::model_categories::ModelCategoryToken;

use crate::configs::static_model::categories::synthetic_category_list::SYNTHETIC_CATEGORY_LIST;
use crate::http_server::common_responses::common_web_error::CommonWebError;
use crate::state::cached_queries::list_cached_tts_categories_for_public_dropdown::list_cached_tts_categories_for_public_dropdown_db_pool;
use crate::state::server_state::ServerState;

// =============== Success Response ===============

#[derive(Serialize)]
pub struct ListTtsCategoriesResponse {
  pub success: bool,
  pub categories: Vec<DisplayCategory>,
}

/// Public-facing and optimized (non-irrelevant fields) category list
/// Used for the main TTS dropdown as well as the TTS edit/tagging UI
#[derive(Serialize, Clone)]
pub struct DisplayCategory {
  pub category_token: ModelCategoryToken,
  pub maybe_super_category_token: Option<ModelCategoryToken>,

  pub model_type: ModelType,

  pub name: String,

  /// Instead of making the frontend deal with "maybe_dropdown_name", always use this:
  pub name_for_dropdown: String,

  pub can_directly_have_models: bool,
  pub can_have_subcategories: bool,
  pub can_only_mods_apply: bool,

  // Moderator fields
  // It's okay to leak this since we do for assigned categories and for mods to see
  // which assigned categories might be invalid.
  pub is_mod_approved: Option<bool>,

  /// False if the category lives in the database, true if the model was generated by code
  pub is_synthetic: bool,

  /// Whether the frontend should alphabetically sort the TTS models.
  pub should_be_sorted: bool,

  pub created_at: DateTime<Utc>,
  pub updated_at: DateTime<Utc>,
  pub deleted_at: Option<DateTime<Utc>>,
}

// =============== Error Response ===============
// NB: Not using derive_more::Display since Clion doesn't understand it.
// =============== Handler ===============

pub async fn list_tts_categories_handler(
  _http_request: HttpRequest,
  server_state: web::Data<Arc<ServerState>>) -> Result<HttpResponse, CommonWebError>
{
  let database_categories = list_cached_tts_categories_for_public_dropdown_db_pool(
    &server_state.caches.ephemeral.database_tts_category_list, &server_state.mysql_pool)
      .await
      .map_err(|e| {
        error!("error querying categories from db/cache: {:?}", e);
        CommonWebError::from_anyhow_error(e)
      })?;

  // NB: These will be already sorted.
  // Transform them to be display-appropriate.
  let mut categories = database_categories.categories.iter()
      .map(|c| {
        DisplayCategory {
          category_token: ModelCategoryToken::new_from_str(&c.category_token),
          // NB: Unwrap default of TTS because we don't have other types yet.
          model_type: ModelType::from_str(&c.model_type)
              .unwrap_or(ModelType::Tts),
          maybe_super_category_token: c.maybe_super_category_token
              .as_deref()
              .map(|t| ModelCategoryToken::new_from_str(t)),
          can_directly_have_models: c.can_directly_have_models,
          can_have_subcategories: c.can_have_subcategories,
          can_only_mods_apply: c.can_only_mods_apply,
          is_mod_approved: c.is_mod_approved,
          is_synthetic: false,
          name: c.name.clone(),
          // NB: Always populate dropdown name instead of leaving it as an optional.
          // This way we can always rely on it to be authoritative for dropdowns.
          name_for_dropdown: c.maybe_dropdown_name
              .clone()
              .unwrap_or(c.name.clone()),
          should_be_sorted: true,
          created_at: c.created_at,
          updated_at: c.updated_at,
          deleted_at: c.deleted_at,
        }
      })
      .collect::<Vec<DisplayCategory>>();

  // Add the synthetic categories at bottom.
  SYNTHETIC_CATEGORY_LIST.iter()
      .for_each(|category| {
        categories.push(DisplayCategory {
          category_token: ModelCategoryToken::new_from_str(category.category_token),
          maybe_super_category_token: category.maybe_super_category_token
              .map(|token| ModelCategoryToken::new_from_str(token)),
          model_type: category.model_type,
          name: category.name.to_string(),
          name_for_dropdown: category.name_for_dropdown.to_string(),
          can_directly_have_models: category.can_directly_have_models,
          can_have_subcategories: category.can_directly_have_subcategories,
          can_only_mods_apply: true,
          is_mod_approved: None,
          is_synthetic: true,
          should_be_sorted: category.should_be_sorted,
          created_at: *CHRONO_DATETIME_UNIX_EPOCH,
          updated_at: *CHRONO_DATETIME_UNIX_EPOCH,
          deleted_at: None,
        });
      });

  let response = ListTtsCategoriesResponse {
    success: true,
    categories,
  };

  let body = serde_json::to_string(&response)
      .map_err(CommonWebError::from_error)?;

  Ok(HttpResponse::Ok()
      .content_type("application/json")
      .body(body))
}
