import { defineTunables } from "@/lib/tuner";

// Structure knobs — changing these rebuilds the tick track / word layouts
// (consumers subscribe and debounce, same pattern as the hero wall).
export const rulerLayoutTuner = defineTunables("rulerLayout", "Ruler layout", {
  side: {
    label: "Side 0=L 1=R",
    min: 0,
    max: 1,
    step: 1,
    default: 1,
    info: "Which viewport edge the ruler lives on: 0 = left, 1 = right.",
  },
  railW: {
    label: "Rail width px",
    min: 32,
    max: 96,
    step: 2,
    default: 48,
    info: "Width of the tick rail at the viewport edge; also the gutter reserved from page content.",
  },
  minorPct: {
    label: "Tick every %",
    min: 0.5,
    max: 5,
    step: 0.5,
    default: 1,
    info: "Scroll-percent spacing between minor ticks on the rail.",
  },
  labelPct: {
    label: "Label every %",
    min: 5,
    max: 25,
    step: 5,
    default: 10,
    info: "Scroll-percent spacing between the longer, number-labeled major ticks.",
  },
  thresholdPct: {
    label: "Flip line vh%",
    min: 4,
    max: 40,
    step: 1,
    default: 12,
    info: "Viewport-height % from the top where a riding word flips horizontal into the top stack.",
  },
  headingPx: {
    label: "Heading px",
    min: 12,
    max: 34,
    step: 1,
    default: 20,
    info: "Font size of the full-size current-section heading below the top pile.",
  },
  ridingPx: {
    label: "Riding px",
    min: 9,
    max: 24,
    step: 1,
    default: 13,
    info: "Font size of the vertical word riding the rail with its section.",
  },
  queuePx: {
    label: "Queue px",
    min: 9,
    max: 24,
    step: 1,
    default: 12,
    info: "Font size of the compact heading links (bottom queue and top pile).",
  },
  topPad: {
    label: "Top pad px",
    min: 4,
    max: 120,
    step: 4,
    default: 20,
    info: "Gap between the nav bar and the first heading in the top pile.",
  },
  currentGap: {
    label: "Current gap px",
    min: 8,
    max: 80,
    step: 2,
    default: 26,
    info: "Extra gap separating the full-size current heading from the compact pile above it.",
  },
  queueSlot: {
    label: "Queue slot px",
    min: 12,
    max: 48,
    step: 2,
    default: 22,
    info: "Vertical spacing between stacked heading links, top pile and bottom queue alike.",
  },
  queuePad: {
    label: "Queue bottom px",
    min: 8,
    max: 120,
    step: 4,
    default: 28,
    info: "Gap between the viewport bottom and the lowest queued heading.",
  },
  textPad: {
    label: "Text pad px",
    min: 0,
    max: 48,
    step: 2,
    default: 14,
    info: "Horizontal gap between the tick rail and the heading text.",
  },
  heroOffset: {
    label: "Hero anchor up px",
    min: 0,
    max: 900,
    step: 20,
    default: 260,
    info: "How far above the hero section's bottom the ARTCRAFT word anchors — larger = the wordmark handoff starts earlier.",
  },
});

// Feel knobs — read per frame.
export const rulerMotionTuner = defineTunables("rulerMotion", "Ruler motion", {
  flipZone: {
    label: "Flip zone px",
    min: 60,
    max: 600,
    step: 10,
    default: 180,
    info: "Scroll distance over which the vertical-to-horizontal top flip plays out.",
  },
  detachZone: {
    label: "Detach zone px",
    min: 60,
    max: 600,
    step: 10,
    default: 220,
    info: "Scroll distance over which a queued heading morphs onto the rail beside its slot.",
  },
  stagger: {
    label: "Letter stagger",
    min: 0,
    max: 0.3,
    step: 0.01,
    default: 0.1,
    info: "Per-letter delay fraction in flips — higher = letters travel more one-by-one.",
  },
  arc: {
    label: "Curve arc px",
    min: 0,
    max: 200,
    step: 4,
    default: 56,
    info: "How far each letter's flight path bows inward (toward the page) mid-flip.",
  },
  jumpDur: {
    label: "Jump dur s",
    min: 0.2,
    max: 2.5,
    step: 0.05,
    default: 1,
    info: "Max duration of a click jump (rail or heading link); short hops scale it down.",
  },
  snapDelay: {
    label: "Snap delay ms",
    min: 100,
    max: 1500,
    step: 50,
    default: 400,
    info: "How long scroll must rest with a flip half-done before it auto-resolves.",
  },
  snapDur: {
    label: "Snap dur s",
    min: 0.2,
    max: 2,
    step: 0.05,
    default: 0.7,
    info: "Duration of the damped auto-scroll that resolves a half-done flip.",
  },
  introDur: {
    label: "Intro dur s",
    min: 0.1,
    max: 2,
    step: 0.05,
    default: 0.7,
    info: "Draw-in duration of each tick during the page-load cascade.",
  },
  introStagger: {
    label: "Intro stag s",
    min: 0,
    max: 0.02,
    step: 0.001,
    default: 0.004,
    info: "Delay between successive ticks in the load cascade (top-down).",
  },
  velRadius: {
    label: "Vel radius px",
    min: 0,
    max: 500,
    step: 10,
    default: 180,
    info: "Document distance around the needle within which ticks react to scroll speed.",
  },
  velMax: {
    label: "Vel stretch",
    min: 0,
    max: 2,
    step: 0.05,
    default: 0.6,
    info: "How much fast scrolling stretches the ticks nearest the needle.",
  },
});

// Ink knobs — read per frame.
export const rulerLookTuner = defineTunables("rulerLook", "Ruler look", {
  minorAlpha: {
    label: "Minor alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.3,
    info: "Opacity of the minor ticks.",
  },
  majorAlpha: {
    label: "Major alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.8,
    info: "Opacity of labeled major ticks and the riding section ticks.",
  },
  labelAlpha: {
    label: "Label alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.55,
    info: "Opacity of the mono percent numbers and section index labels.",
  },
  minorLen: {
    label: "Minor len px",
    min: 2,
    max: 20,
    step: 1,
    default: 8,
    info: "Length of minor ticks, drawn from the outer edge.",
  },
  majorLen: {
    label: "Major len px",
    min: 4,
    max: 28,
    step: 1,
    default: 15,
    info: "Length of labeled major ticks, drawn from the outer edge.",
  },
  ghostAlpha: {
    label: "Ghost alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.9,
    info: "Opacity of the hover ghost line previewing where a rail click will jump.",
  },
  queueAlpha: {
    label: "Queue alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.55,
    info: "Opacity of the compact heading links (bottom queue and top pile).",
  },
});
