pub mod handle_successful_fal_webhook;
mod attach_cover_image;
mod attach_prompt_imageref_cover;
mod process_audio_payload;
mod process_image_payload;
mod process_images_payload;
mod process_model_glb_payload;
mod process_model_mesh_payload;
mod process_result_files_payload;
mod process_video_payload;
pub(in crate::http_server::endpoints::webhooks) mod resolve_file_metadata;
