//! These prompts should be fully innocent and allowed

use speculoos::asserting;

use prompt_engineering::classify_prompt::classify_prompt;

#[test]
fn sfw_english_test() {
  // These are actual user prompts that use borderline language, but are safe
  // Eventually we'll want to classify prompts that are sufficiently engineered vs prompts that need enrichment.
  assert_prompts_are_sfw(&[
    "(masterpiece, best quality), 1girl, blonde hair, red dress, pantyhose, cute face, blush",
    "***botw style***  a lifeguard wearing a red one piece swimsuit",
    "***charturnbetalora*** A lifeguard wearing a red one-piece swimsuit",
    "1000 coins inside 50 large jars",
    "1girl, blue hair, sitting on top of a table, smile",
    "1girl, purple hair, school uniform, smug, looking at viewer, heterochromia",
    "1girl, red hair, city streets",
    "1girl, schoolgirl, blue hair, eating icecream",
    "1girl, steampunk, holding a wrench",
    "2 titans are looking at the sunset",
    "2d hand drawn disney princess covered in chocolate, peanuts and corn",
    "2Pac in today's world.",
    "3 dancing people in a concert",
    "<lora:tachie:0.7>, ",
    "A 12 ft tall terrifying shadow analog horror demon",
    "A badger in an explorer's hat and a fawn",
    "A boy eating a ice cream at the palace",
    "A boy, yellow short hair, blue eyes a star in it, hikaru kamiki",
    "A crowd of 100 people looking at the camera",
    "A cute pug with an owner",
    "A cute small fox in the woods",
    "A female inkling wearing a pink one-piece swimsuit",
    "A giant bee and a small dog",
    "A girl from Robotech universe, SDF1 mecha superdimensional fortess",
    "A happy girl in a park",
    "a kid crying for his ice cream in the floor, the seller is laughing in his car",
    "a little Teddy throwing a blue ball",
    "A little Unicorn playing in the Sand",
    "A man is happy at the press conference",
    "A man selling rotten milk in the park",
    "a man that is also a car",
    "A real life pikachu being walked like a dog.",
    "A robotic girl with blue eyes.",
    "A shark getting attacked by a vending machine.",
    "A white cat, standing on its legs and holding a diamond sword.",
    "A woman of KRON4",
    "ai hoshino sleeping",
    "Alastor from Hazbin Hotel, drinking out of a cup",
    "Albert Einstein",
    "Alex Jones wearing a Minecraft styled duck hat",
    "An adorable chubby fawn laying on a patch of grass smiling",
    "An eboost monkey",
    "An extreme close-up of an gray-haired man with a beard in his 60s, he is deep in thought pondering the history of the universe as he sits at a cafe in Paris, his eyes focus on people offscreen as they walk as he sits mostly motionless, he is dressed in a wool coat suit coat with a button-down shirt , he wears a brown beret and glasses and has a very professorial appearance, and the end he offers a subtle closed-mouth smile as if he found the answer to the mystery of life, the lighting is very cinematic with the golden light and the Parisian streets and city in the background, depth of field, cinematic 35mm film.",
    "an image of kojiro hiuga kicking tsubasa osora in the stomach",
    "an island in the sun with surver and chamäleon",
    "Animated character in the style of VivziePop",
    "Anime girl with pink hair and blue eyes with green eyes with a kawaii outfit reading in her bedroom full of posters.",
    "anime, hand-drawn and cel animation techniques, iron man from marvel, natural design, beautifully rendered and expressive rich colors, vibrant pastel colors, imaginative and fantastical landscapes, sharp attention to detail, realism and a strong sense of nostalgia and warmth, sharp attention to small details and textures, fantastical creatures, settings, depth and emotions emphasized and accentuated by lighting and shading, extremely high quality, incredibly high finite definition, high resolution, hand-drawn and cel animation techniques",
    "Archaic warriors on horseback kidnap Sabine maidens",
    "Baldi, showing his anger by slapping with his ruler.",
    "Batman in iran",
    "Beautiful Woman with blue hair and green eyes dressed kawaii dress smiling wearing cat ears and tail.",
    "Big booty joe",
    "Black and white image of a motor cycle in the year 1955",
    "Blue apple",
    "boy demon black hair wereind a shirt and shorts hands in pokets",
    "Boy named axel davidson has a big belly and a girl called macey steward holds his belly in the sunset",
    "boy with black and blue hair in a red shirt and jeans happy",
    "cary entity floating menacingly, with many floating eyes and red flesh tentacles and spikes coming out of it, with many mouths with very spiky teeth.",
    "Charlie Morningstar from Hazbin Hotel",
    "Clark Gable smiling in a nineteen twenties nightclub.",
    "Classic painting of 2 brown rabbits with white spots wearing overalls and a dress, carrying basket of carrots, outdoors, Monet",
    "crab human man model realistic",
    "Cute White Shepherd Dog, Standing, Blue Pants, Blue Shoes",
    "Cute Wolf, Blue cap, Grey Fur, White Cream, Blue Tracksuit, Blue Pants, Wolf Tail, Red Shoes",
    "Cute Wolf, Blue cap, Light grey fur, Blue Tracksuit, Blue pants, Red shoes, wolf tail",
    "Cute, Muscular wolf, Male, Blue cap, Light grey fur, Blue Tracksuit, Red shoes, Blue pants, Wolf tail, Smiling",
    "dead girl in a white dress with blood comeing frome her head in an abendend hospitel",
    "demon girl with white hair light blue eyes with red horns and a tail in a castel",
    "Dog with horns",
    "Doki Doki Literature club",
    "Donald Duck, riding on a yellow submarine",
    "Donald Trump riding a t-rex while  holding a gun with American flags in the background",
    "Dragon ball",
    "drone",
    "Dwight D. Eisenhower, looking at the camera, realistic, high quality",
    "Eazy-E wearing a Cuban Link, Rolex, and white Nike's with a AR-15 in his left hand.",
    "Elsa Plush Doll!",
    "Engineer Team Fortress 2",
    "Eraser BFDI drunk",
    "Eren Jaeger vs titans",
    "Farmers with big Harvester machines",
    "female, witch, holding flintlock pistol",
    "Foxdog, Wolfdog",
    "Foxy from five nights at Freddy’s eating a burger",
    "freddy fazbear watching a movie",
    "Friendly Monsters with long hair in front of mount fujii",
    "Funny looking feff",
    "Furry",
    "Generate what would Eazy-E would look like today",
    "Giant anime hamburger attacking Los Angeles",
    "Giant girl baby destroying the city",
    "Giantess acting like titan on attack on titan",
    "girl hair pink , dance , japan",
    "girl in a pink sweter and jeans with pink horns looking window with durtyblond hair saprized",
    "girl in a prom dress crying in the rain",
    "girl siting in a light blue dress",
    "girl teen in a dress with horns and a tail in a feald of flowers",
    "girl with bloned hair wering a light blue dress whell drawing with a boy with black hair wering a red shirt siting nex to her",
    "girl with horns and a tail that has durdyblond hair wereing a pink sweter and riped jeans",
    "girl with lightblue hair cute",
    "girl with white hair and lifght blue eyes in a light blue dress with horns & a tail in a feld of flowers with a human boy",
    "Glamorous white gold and pink themed room",
    "Gogeta eating a chili dog",
    "Grimreper human boy",
    "Grover, Sesame Street",
    "Guy Hamdon/SheZow (SheZow form) riding a motorcycle in a highway, anime style",
    "Hank Hill in armor closeup",
    "Has short yellow hair, blue eyes a star in it, Teenager",
    "Hatsune Miku",
    "Hexagon globe of the world",
    "Hey what is up?",
    "HopeScope Wedding Plush Doll",
    "Horse running on a race track",
    "I really tall old man. He is at least 13 feet tall, and with his familiy in a family photo. The next tallest member is 4 foot, so he is MASSIVE. He looks like a slitherman, but white old man",
    "I’m a feff",
    "James Dean smiling wearing a cowboy hat.",
    "Joe Biden flying as Superman",
    "Jolyne Cujoh flying on top of the apple tree",
    "Kanye West and Jay-Z in Paris, France at the Eiffel Tower.",
    "kawaii anime frog",
    "kinda bug and kinda snack.",
    "kirby fighting plankton",
    "LGBTQ Appreciation",
    "Lightning mcqueen from pixar cars but as an anime",
    "Link",
    "lovander palworld",
    "magical animal",
    "Maid with the prince standing next to her",
    "Make Huggy Wuggy From Poppy Playtime: Chapter 1.",
    "Man eating soup at a bagel shop on a sunny day",
    "Man standing on the edge of a cliff",
    "Man with slicked back black hair and blue eyes with a black puppy while smiling.",
    "mank walking",
    "Maroon 5 playing on the jimmy fallon stage",
    "masterpiece, best quality, white dress, plump,",
    "Me",
    "monkey playing fortnite",
    "morbidly obese blonde woman",
    "Nahida from genshin impact",
    "Nami from one peice on the beach angry",
    "Overweight Taco Bell manager Female. Hair and a bun with braces, smiling. Black uniform with apron.",
    "person waving",
    "pichu witch pockimon",
    "plum (plum landing) at comic con",
    "President Putin riding on a Canguru",
    "pride flag  real flag",
    "Princess Peach",
    "Rat mixed with sharks",
    "Red Dragon",
    "red witch goat, purple eyes, round glasses, furry, young",
    "REDHEAD",
    "Richard Nixon holding a Super Mario lucky block",
    "Ronald McDonald holding a taco ",
    "Ronald Reagan standing in front of a Lamborghini Aventador, realistic, high quality, heaven",
    "Ronald Reagan, looking at the camera, sitting on a duck floatie in a pool, realistic",
    "Samurai and geisha riding on a horse",
    "Scary, fear, horror, creepypasta, spooky",
    "scrap company",
    "Serbian musician star named Desingerica with wings and blade in his hands",
    "Sexy latin girl in bikini, who's posing and take a pictures.",
    "SheZow standing next to Christ the Redeemer, CGI render",
    "Shigeru Miyamoto fighting through a crowd of nerds",
    "skibidi toilet rizzed up ohio",
    "Solid snake eating a hamburger",
    "Sonic beats up Mario",
    "Sonic meets the Powerpuff Girls",
    "Sonic the hedgehog going fast",
    "sunnyv2, man working in the office",
    "sunnyv2, stunning close-up portrait of a swiss business woman with captivating eyes, background is a bright office",
    "The biggest of biggest guys",
    "The father in my dreams ! I love my father ! I hug him but... He does't hug me !",
    "The healthiest hamburger in all the land",
    "The Rock eating rocks.",
    "The slimer hugging an eel",
    "the wiggles dancing",
    "Tifa and aerith. Bikini. Laughing. Squirting sunscreen on each other",
    "touhou project, marisa kirisame, forest background",
    "Transfur",
    "tree people",
    "trump riding and hanging out the window in a doge charger with an AR-15 pointed in the air shooting with American flags all over the place.",
    "Ultra HD, very high resolution, photorealistic real life picture, very detailed face, wide shot photography of a huge, enormous, extremely muscular, supermassive, obese, good nature, shirtless, handsome 54 year old welsh wrestling-coach taking a selfie with his new iphone, welsh cocky alpha-male, superheavyweight-offseason-bodybuilder body shape, giant supermassive ultrabroad superflabby pointy pectorals, extremamente mamiludo , beer belly, immense massive muscular legs, mamilos enormes hiper-inchados protuberantes, sideburns, extremely high testosterone levels, very masculine face, side-parted tight hair",
    "verey fansey dresses",
    "Victorian era portrait of an thai woman",
    "Wedding Dress",
    "White and blue fox furry in a river",
    "White German Shepherd, Back View, Tail up",
    "white rabbit speaking into studio mic",
    "White Shepherd Dog, Green Sport Coat, Blue Pants, Blue Shoes",
    "will smith slapping Donald Trump at the Oscars. 4k, realistic",
    "Woman with blue hair and green eyes dressed kawaii dress smiling wearing cat ears and tail.",
    "Woman with pink and blue hair and green eyes dressed kawaii dress holding a kitten while smiling.",
    "World's biggest Mountain Dew Baja Blast",
    "XXXTENTACION",
    "YOU ARE AWSOME",
    "Young John F. Kennedy smoking a cigar in a nineteen forties club.",
    "young wizard using magic with hands",
    "Young woman with pink and blue hair and green eyes dressed kawaii Japanese singing into a microphone at a concert.",
    "Yui and Hideki from Angel Beats holding hands while smiling.",
    "Zelda",
    "\"Stone Cold\" Steve Austin holding a Big Mac",
  ]);
}

#[test]
fn sfw_spanish_test() {
  // These are actual user prompts that use borderline language, but are safe
  // Eventually we'll want to classify prompts that are sufficiently engineered vs prompts that need enrichment.
  assert_prompts_are_sfw(&[
    "como tan muchacho", // NB: "like such a boy"
    "gata gata negra antropomorfica de ojos verdes y peinado bob color blanco peinado blanco vestida con un uniforme escolar japones estilo anime",
    "perro volando en las nuves", // NB: Dog flying in the clouds
    "rio con personas", // NB: "river with people"
    "Uma mulher chorando", // NB: "A woman crying"
    "Una mujer con piel de dragon, y cuernos", // NB: "A woman with dragon skin and horns"
    "Una mujer japonesa embarazada pero más femenina con cabello blanco, ojos azules, un traje rojo de artes marciales de cuerpo completo, una cicatriz en la mejilla, con un efecto de nieve en el fondo de ciudad, en estilo de dibujo manga",
    "Una persona con un brazo arancado caminando", // NB: A person with a torn arm walking
  ]);
}


fn assert_prompts_are_sfw(prompts: &[&str]) {
  for prompt in prompts {
    let classification = classify_prompt(prompt);

    asserting(&format!("is abusive - prompt: {}", prompt))
        .that(&classification.is_abusive())
        .is_equal_to(false);

    asserting(&format!("is child abuse - prompt: {}", prompt))
        .that(&classification.is_child_abuse())
        .is_equal_to(false);
  }
}
