use std::marker::PhantomData;

use sqlx::{Executor, MySql};

use tokens::tokens::folders::FolderToken;
use tokens::tokens::users::UserToken;

pub struct InsertFolderArgs<'e, 'c, E>
where
  E: 'e + Executor<'c, Database = MySql>,
{
  pub name: &'e str,
  pub owner_user_token: &'e UserToken,
  pub maybe_parent_folder_token: Option<&'e FolderToken>,
  pub maybe_color_code: Option<&'e str>,
  pub mysql_executor: E,
  pub phantom: PhantomData<&'c E>,
}

/// Insert a new folder row. The token is generated by this function and
/// returned to the caller (mints in the data-access layer, not the handler).
pub async fn insert_folder<'e, 'c: 'e, E>(
  args: InsertFolderArgs<'e, 'c, E>,
) -> Result<FolderToken, sqlx::Error>
where
  E: 'e + Executor<'c, Database = MySql>,
{
  let token = FolderToken::generate();

  sqlx::query!(
    r#"
INSERT INTO folders
SET
  token = ?,
  name = ?,
  owner_user_token = ?,
  maybe_parent_folder_token = ?,
  maybe_color_code = ?
    "#,
    token.as_str(),
    args.name,
    args.owner_user_token.as_str(),
    args.maybe_parent_folder_token.map(|t| t.as_str()),
    args.maybe_color_code,
  )
    .execute(args.mysql_executor)
    .await?;

  Ok(token)
}
