// Every tweakable constant of the hero galaxy, registered with the dev
// tuner (see TUNER.md). Defaults here ARE the shipped values — tune live,
// copy the JSON from the panel, then update the defaults.

import { defineTunables } from "@/lib/tuner";

// Structure knobs — changing these rebuilds the arm paths, tick marks, and
// card roster (debounced).
export const galaxyLayoutTuner = defineTunables(
  "galaxyLayout",
  "Galaxy layout",
  {
    arms: {
      label: "Arms",
      min: 2,
      max: 6,
      step: 1,
      default: 6,
      info: "How many spiral arms emanate from the center; cards are dealt across them round-robin.",
    },
    turns: {
      label: "Turns per arm",
      min: 0.4,
      max: 2.5,
      step: 0.05,
      default: 1.05,
      info: "How many revolutions each arm makes from origin to outer end — lower is straighter rays, higher is a tighter swirl.",
    },
    rMaxFrac: {
      label: "Track pitch",
      min: 0.4,
      max: 1.2,
      step: 0.02,
      default: 0.7,
      info: "Sets the spiral's tightness: the radius the drawn windings span, as a fraction of the viewport half-diagonal. Larger = wider winding gaps = bigger cards. Cards travel past it until fully offscreen.",
    },
    birthFrac: {
      label: "Birth radius",
      min: 0.02,
      max: 0.4,
      step: 0.01,
      default: 0.08,
      info: "Where cards are born, as a fraction of the outer radius — the nebula pocket around the wordmark.",
    },
    cardN: {
      label: "Card count",
      min: 8,
      max: 48,
      step: 1,
      default: 32,
      info: "Total cards riding the arms at once.",
    },
    cardHFrac: {
      label: "Card h cap",
      min: 0.08,
      max: 0.35,
      step: 0.005,
      default: 0.185,
      info: "Absolute card height ceiling as a fraction of the viewport height — the track-gap math sizes cards below this so they never collide.",
    },
    armJitter: {
      label: "Arm desync",
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.13,
      info: "Per-arm conveyor phase offset — 0 makes all arms birth cards in lockstep rings, higher desynchronizes them.",
    },
    ticksPerArm: {
      label: "Ticks / arm",
      min: 0,
      max: 40,
      step: 1,
      default: 14,
      info: "Tick marks straddling each arm's outer half in the line underlay (0 = none).",
    },
    circFrac: {
      label: "Constr circle",
      min: 0.2,
      max: 1,
      step: 0.02,
      default: 0.56,
      info: "Radius of the dashed construction circle in the underlay, as a fraction of the outer radius.",
    },
  },
);

// Feel knobs — read per frame.
export const galaxyMotionTuner = defineTunables(
  "galaxyMotion",
  "Galaxy motion",
  {
    idleSpeed: {
      label: "Idle cyc/min",
      min: 0,
      max: 0.8,
      step: 0.01,
      default: 0.57,
      info: "Unattended conveyor speed — full journeys (birth to edge) per minute.",
    },
    scrub: {
      label: "Scrub /1kpx",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.2,
      info: "Conveyor journeys advanced per 1000px of scroll — scroll-linked and reversible.",
    },
    spinDeg: {
      label: "Spin °/min",
      min: -60,
      max: 60,
      step: 0.5,
      default: -50,
      info: "Slow global rotation of the whole system (arms, ticks, and card paths together); cards themselves stay upright.",
    },
    wobbleAmp: {
      label: "Wobble px",
      min: 0,
      max: 40,
      step: 1,
      default: 0,
      info: "How far cards drift off their exact arm position. Off by default — the layout owes its collision guarantee to cards staying on track; a fallback flavor knob only.",
    },
    wobbleFreq: {
      label: "Wobble Hz",
      min: 0,
      max: 2,
      step: 0.05,
      default: 0.25,
      info: "Speed of the floating drift.",
    },
    introDelay: {
      label: "Intro delay s",
      min: 0,
      max: 2,
      step: 0.05,
      default: 0.2,
      info: "Pause before the first card arrives on load.",
    },
    introStagger: {
      label: "Intro stag s",
      min: 0,
      max: 0.3,
      step: 0.01,
      default: 0.08,
      info: "Delay between successive cards arriving during the intro.",
    },
    introDur: {
      label: "Intro fade s",
      min: 0.2,
      max: 2,
      step: 0.05,
      default: 0.6,
      info: "Fade-in duration of each card during the intro.",
    },
  },
);

// Ink and lens knobs — read per frame.
export const galaxyLookTuner = defineTunables("galaxyLook", "Galaxy look", {
  density: {
    label: "Density",
    min: 0.3,
    max: 1,
    step: 0.02,
    default: 0.82,
    info: "Fraction of the gap to its nearest neighbor each card may fill — higher packs the screen tighter, lower gives more air. Collision-free across the whole range (at 1.0 cards may kiss edges).",
  },
  cornerPx: {
    label: "Corner px",
    min: 0,
    max: 24,
    step: 1,
    default: 10,
    info: "Corner radius of each card (and its hairline frame), in px — the one deliberate exception to the site's zero-radius rule.",
  },
  innerCap: {
    label: "Inner cap",
    min: 0.2,
    max: 1,
    step: 0.02,
    default: 0.45,
    info: "Size ceiling for newborn cards as a fraction of the full cap, ramping up over the journey — keeps inner cards smaller than outer ones even when space would allow more.",
  },
  aspectEnd: {
    label: "Square until",
    min: 0.05,
    max: 0.8,
    step: 0.01,
    default: 0.3,
    info: "Journey fraction over which a newborn card morphs from a rounded square into its full 16:9 aspect.",
  },
  blurMax: {
    label: "Blur max",
    min: 0,
    max: 0.25,
    step: 0.005,
    default: 0.09,
    info: "Blur radius (in card-UV units) at birth — the nebula softness at the center; also the blur a still-loading card holds.",
  },
  blurEnd: {
    label: "Blur end",
    min: 0.05,
    max: 0.9,
    step: 0.01,
    default: 0.18,
    info: "Journey fraction where the blur fully resolves to sharp.",
  },
  playFrac: {
    label: "Play from",
    min: 0,
    max: 1,
    step: 0.02,
    default: 0.42,
    info: "Journey fraction past which a card's clip earns a live decoder — inner blurred cards hold a frozen frame.",
  },
  washInner: {
    label: "Inner wash",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.7,
    info: "Card presence at birth — newborn cards sit faint near the origin and solidify as they emerge.",
  },
  fadeBand: {
    label: "Birth fade",
    min: 0.02,
    max: 0.3,
    step: 0.01,
    default: 0.09,
    info: "Fraction of the journey over which a newborn card fades in at the center. There is no exit fade — cards die fully offscreen.",
  },
  dim: {
    label: "Footage dim",
    min: 0,
    max: 1,
    step: 0.02,
    default: 1,
    info: "Overall footage strength (dark theme dims via color, light theme washes via opacity).",
  },
  aberration: {
    label: "Dispersion",
    min: 0,
    max: 0.06,
    step: 0.001,
    default: 0.019,
    info: "Chromatic aberration strength toward each card's edges — the cheap lens-dispersion detail.",
  },
  curvePx: {
    label: "Curve px",
    min: 0,
    max: 160,
    step: 1,
    default: 80,
    info: "How far each card's center bows toward the camera — the slight lens-warp of the plane.",
  },
  frameAlpha: {
    label: "Frame alpha",
    min: 0,
    max: 1,
    step: 0.02,
    default: 0.22,
    info: "Strength of the hairline frame drawn along each card's (rounded) edge.",
  },
  lineAlpha: {
    label: "Line alpha",
    min: 0,
    max: 1,
    step: 0.02,
    default: 0.26,
    info: "Opacity of the arm guide curves and construction circle in the underlay — 0 kills the geometric layer entirely.",
  },
  tickAlpha: {
    label: "Tick alpha",
    min: 0,
    max: 1,
    step: 0.02,
    default: 0.5,
    info: "Opacity of the tick marks along the arms.",
  },
});
