// Every tweakable constant of the hero blueprint spiral, registered with the
// dev tuner (see TUNER.md). Defaults here ARE the shipped values — tune live,
// copy the JSON from the panel, then update the defaults.

import { defineTunables } from "@/lib/tuner";

// Drawing structure — changing these re-renders the SVG linework and the
// cards' base placement.
export const spiralLayoutTuner = defineTunables(
  "spiralLayout",
  "Spiral layout",
  {
    cx: {
      label: "Center x ×w",
      min: 0.3,
      max: 1,
      step: 0.01,
      default: 0.66,
      info: "Horizontal position of the spiral's origin, as a fraction of the stage width.",
    },
    cy: {
      label: "Center y ×h",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.5,
      info: "Vertical position of the spiral's origin, as a fraction of the stage height.",
    },
    turns: {
      label: "Windings",
      min: 1.5,
      max: 5,
      step: 0.25,
      default: 3,
      info: "How many full revolutions the spiral makes from origin to outer end.",
    },
    rMax: {
      label: "Outer r px",
      min: 300,
      max: 1000,
      step: 10,
      default: 700,
      info: "Radius of the spiral's outer end, in stage units (1600×900 stage) — larger bleeds further past the viewport edges.",
    },
    phaseDeg: {
      label: "Phase °",
      min: 0,
      max: 360,
      step: 5,
      default: 210,
      info: "Rotates the whole drawing — sets which direction the spiral's outer end exits the stage.",
    },
    birthFrac: {
      label: "Birth radius",
      min: 0.05,
      max: 0.6,
      step: 0.01,
      default: 0.22,
      info: "Where cards are born, as a fraction of the outer radius — below this the spiral is linework only.",
    },
    tickDeg: {
      label: "Tick every °",
      min: 5,
      max: 45,
      step: 1,
      default: 10,
      info: "Angular spacing of the ticks marked along the spiral's outer windings.",
    },
    majorEvery: {
      label: "Major every n",
      min: 2,
      max: 6,
      step: 1,
      default: 3,
      info: "Every n-th tick is a longer major with a degree label.",
    },
    tickLen: {
      label: "Tick len px",
      min: 3,
      max: 24,
      step: 1,
      default: 8,
      info: "Length of minor ticks straddling the curve, in stage units; majors are twice this.",
    },
    tickMinFrac: {
      label: "Ticks from r",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.4,
      info: "Ticks only appear outside this fraction of the outer radius — the tight inner windings stay clean.",
    },
    constrFrac: {
      label: "Constr circle",
      min: 0.2,
      max: 1,
      step: 0.02,
      default: 0.62,
      info: "Radius of the dashed construction circle, as a fraction of the outer radius.",
    },
    radDeg: {
      label: "R callout °",
      min: 0,
      max: 360,
      step: 5,
      default: 20,
      info: "Angle at which the radius dimension line and its R label are drawn.",
    },
    cardN: {
      label: "Card count",
      min: 3,
      max: 12,
      step: 1,
      default: 7,
      info: "How many render cards ride the spiral conveyor at once.",
    },
    cardW: {
      label: "Card w px",
      min: 80,
      max: 320,
      step: 5,
      default: 190,
      info: "Full-grown card width in stage units; cards are born smaller (see min scale).",
    },
    exclX: {
      label: "Excl x ×w",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.42,
      info: "Cards fade out left of this stage-width fraction when also below the exclusion y — keeps footage from crawling under the copy block.",
    },
    exclY: {
      label: "Excl y ×h",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.52,
      info: "Top edge of the copy-block exclusion zone, as a fraction of the stage height.",
    },
    exclFeather: {
      label: "Excl feather",
      min: 10,
      max: 400,
      step: 10,
      default: 160,
      info: "Softness of the exclusion fade, in stage units — cards dim gradually as they enter the zone.",
    },
  },
);

// Feel knobs — read per frame.
export const spiralMotionTuner = defineTunables(
  "spiralMotion",
  "Spiral motion",
  {
    idleSpeed: {
      label: "Idle cyc/min",
      min: 0,
      max: 0.6,
      step: 0.01,
      default: 0.12,
      info: "Unattended conveyor speed — full journeys (birth to edge) per minute; the mechanical drift that keeps the drawing alive.",
    },
    scrub: {
      label: "Scrub /1kpx",
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.18,
      info: "Conveyor journeys advanced per 1000px of scroll — scroll-linked and reversible.",
    },
    introDur: {
      label: "Draw dur s",
      min: 0.2,
      max: 3,
      step: 0.05,
      default: 1.4,
      info: "Duration of the spiral line's dash-draw from origin to outer end on load.",
    },
    introStagger: {
      label: "Card stag s",
      min: 0,
      max: 0.3,
      step: 0.01,
      default: 0.07,
      info: "Delay between successive cards arriving during the intro.",
    },
    introDelay: {
      label: "Cards after s",
      min: 0,
      max: 2,
      step: 0.05,
      default: 0.4,
      info: "How long after the line starts drawing the first card arrives.",
    },
  },
);

// Ink knobs — read per frame / applied at render.
export const spiralLookTuner = defineTunables("spiralLook", "Spiral look", {
  lineAlpha: {
    label: "Line alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.5,
    info: "Opacity of the main spiral hairline.",
  },
  tickAlpha: {
    label: "Tick alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.6,
    info: "Opacity of the ticks along the curve.",
  },
  labelAlpha: {
    label: "Label alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.5,
    info: "Opacity of the mono degree labels and annotation text.",
  },
  constrAlpha: {
    label: "Constr alpha",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.35,
    info: "Opacity of the dashed construction circle and the radius dimension line.",
  },
  minScale: {
    label: "Birth scale",
    min: 0.3,
    max: 1,
    step: 0.02,
    default: 0.55,
    info: "Card scale at birth near the origin; cards grow to full size as they wind outward.",
  },
  washInner: {
    label: "Inner wash",
    min: 0,
    max: 1,
    step: 0.05,
    default: 0.35,
    info: "Card opacity at birth — newborn cards sit faint near the origin and sharpen as they emerge.",
  },
  fadeBand: {
    label: "Fade band",
    min: 0.02,
    max: 0.3,
    step: 0.01,
    default: 0.1,
    info: "Fraction of the journey over which cards fade in at birth and out at the outer edge — also hides the conveyor wrap.",
  },
});
