// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";

const SERVER_MUST_NOT_IMPORT_FAKE = {
  "no-restricted-imports": [
    "error",
    {
      patterns: [
        {
          group: ["**/fake-upstream/**", "@artcraft/mcp-fake-upstream"],
          message:
            "The MCP server must never import the fake upstream. It is a separate deployable; see mcp/CLAUDE.md (Environments).",
        },
      ],
    },
  ],
};

const FAKE_MUST_NOT_IMPORT_SERVER = {
  "no-restricted-imports": [
    "error",
    {
      patterns: [
        {
          group: ["**/src/**", "@artcraft/mcp"],
          message:
            "The fake upstream must not import server code; keep the boundary one-directional.",
        },
      ],
    },
  ],
};

export default tseslint.config(
  {
    ignores: [
      "node_modules/",
      ".wrangler/",
      "dist/",
      "coverage/",
      "fake-upstream/node_modules/",
      "worker-configuration.d.ts", // generated by `wrangler types`
      "fake-upstream/worker-configuration.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  { files: ["eslint.config.js"], ...tseslint.configs.disableTypeChecked },
  { files: ["src/**/*.ts", "src/**/*.tsx"], rules: SERVER_MUST_NOT_IMPORT_FAKE },
  {
    files: ["fake-upstream/src/**/*.ts", "fake-upstream/src/**/*.tsx"],
    rules: FAKE_MUST_NOT_IMPORT_SERVER,
  },
);
