[package]
name = "logging"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[lib]
# NB: Public "logging" crate is five years old and uninteresting. Stealing this name for internal use.
name = "logging"
path = "src/lib.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[dependencies]
# cargo-hakari workspace hack (faster compile times)
workspace-build-acceleration = { workspace = true }

# Internal
# (None yet)

# External
env_logger = "0.11.3"
trace_id.workspace = true
log = { workspace = true }

[dev-dependencies]
# None yet
