use crate::sessions::anonymous_visitor_tracking::avt_cookie_payload::AvtCookiePayload;
use crate::sessions::anonymous_visitor_tracking::avt_cookie_payload_error::AvtCookiePayloadError;
use jwt_signer::jwt_signer::JwtSigner;

/// Signs and verifies the AVT cookie payload using HMAC-signed JWTs.
/// This module is intentionally HTTP-agnostic. The HTTP / cookie wrapper lives in `avt_cookie_manager`.
#[derive(Clone)]
pub struct AvtPayloadSigner {
  jwt_signer: JwtSigner,
}

impl AvtPayloadSigner {
  pub fn new(hmac_secret: &str) -> Result<Self, AvtCookiePayloadError> {
    Ok(Self {
      jwt_signer: JwtSigner::new(hmac_secret)?,
    })
  }

  pub fn encode(&self, payload: &AvtCookiePayload) -> Result<String, AvtCookiePayloadError> {
    let claims = payload.to_map();
    let jwt_string = self.jwt_signer.claims_to_jwt(&claims)?;
    Ok(jwt_string)
  }

  pub fn decode(&self, jwt: &str) -> Result<AvtCookiePayload, AvtCookiePayloadError> {
    let claims = self.jwt_signer.jwt_to_claims(jwt)?;
    AvtCookiePayload::from_map(claims)
  }
}

#[cfg(test)]
mod tests {
  use crate::sessions::anonymous_visitor_tracking::avt_cookie_payload::AvtCookiePayload;
  use crate::sessions::anonymous_visitor_tracking::avt_payload_signer::AvtPayloadSigner;
  use tokens::tokens::anonymous_visitor_tracking::AnonymousVisitorTrackingToken;

  #[test]
  fn test_encode() {
    // NB: Stable encoding test. If this changes we should bump the cookie version.
    let signer = AvtPayloadSigner::new("fake_secret").unwrap();
    let token = AnonymousVisitorTrackingToken::new_from_str("avt_ex_anonymous_visitor_tracking_token");
    let payload = AvtCookiePayload::from_token(token);

    let encoded = signer.encode(&payload).unwrap();

    assert_eq!(
      encoded,
      "eyJhbGciOiJIUzI1NiJ9.eyJhdnRfdG9rZW4iOiJhdnRfZXhfYW5vbnltb3VzX3Zpc2l0b3JfdHJhY2tpbmdfdG9rZW4iLCJjb29raWVfdmVyc2lvbiI6IjEifQ.5jgQfSXue684okKBzW3847jEhL7eLQKzelyAkgnwe_I"
    );
  }

  #[test]
  fn test_decode_version_1() {
    // NB: Version 1 payload. The expected encoded value below was generated by `test_encode`.
    let payload =
        "eyJhbGciOiJIUzI1NiJ9.eyJhdnRfdG9rZW4iOiJhdnRfZXhfYW5vbnltb3VzX3Zpc2l0b3JfdHJhY2tpbmdfdG9rZW4iLCJjb29raWVfdmVyc2lvbiI6IjEifQ.5jgQfSXue684okKBzW3847jEhL7eLQKzelyAkgnwe_I";

    let signer = AvtPayloadSigner::new("fake_secret").unwrap();
    let decoded = signer.decode(payload).unwrap();

    assert_eq!(decoded.avt_token.as_str(), "avt_ex_anonymous_visitor_tracking_token");
    assert_eq!(decoded.cookie_version, 1);
  }

  #[test]
  fn test_round_trip() {
    let signer = AvtPayloadSigner::new("fake_secret").unwrap();
    let token = AnonymousVisitorTrackingToken::new_from_str("avt_ex_anonymous_visitor_tracking_token");
    let payload = AvtCookiePayload::from_token(token);

    let encoded = signer.encode(&payload).unwrap();
    let decoded = signer.decode(&encoded).unwrap();

    assert_eq!(decoded.avt_token.as_str(), "avt_ex_anonymous_visitor_tracking_token");
    assert_eq!(decoded.cookie_version, 1);
  }
}
