// GENERATED by scripts/gen-api.mjs — do not edit.
// Source: https://storyteller-docs.netlify.app/api.json (trimmed to src/upstream/allowlist.json).
// Regenerate with `pnpm gen:api`; review the diff against the previous snapshot.
export interface paths {
    "/v1/accounts/google_sso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in or sign up with "Sign in with Google" credentials.
         *     This supports both sign up for new users and sign in for existing users.
         */
        post: operations["google_sso_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits/namespace/{namespace}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_session_credits_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job statuses for a batch of multiple job tokens. */
        get: operations["batch_get_inference_job_status_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/job/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the status for a single job. */
        get: operations["get_inference_job_status_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List job statuses for jobs that are associated with the user's session.
         * @description The user must be logged in. This endpoint will only show the last 36 hours
         *     of jobs. Any jobs "dismissed" by the user will not be returned.
         *
         *     This returns jobs of all states: pending, started, attempt_failed,
         *     complete_success, dead, etc.
         */
        get: operations["list_session_jobs_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/cost/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate the cost of an audio generation. */
        post: operations["omni_gen_audio_cost_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/cost/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate the cost of an image generation. */
        post: operations["omni_gen_image_cost_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/cost/mesh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate the cost of a mesh (3D object) generation. */
        post: operations["omni_gen_mesh_cost_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/cost/splat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate the cost of a splat (3D world) generation. */
        post: operations["omni_gen_splat_cost_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/cost/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate the cost of a video generation. */
        post: operations["omni_gen_video_cost_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/models/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available audio models. */
        get: operations["omni_gen_audio_models_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/models/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available image models. */
        get: operations["omni_gen_image_models_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/models/mesh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available mesh (3D object) models. */
        get: operations["omni_gen_mesh_models_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/models/splat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available splat (3D world) models. */
        get: operations["omni_gen_splat_models_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/omni_gen/models/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available video models. */
        get: operations["omni_gen_video_models_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session_info_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/namespace/{namespace}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get subscription for the payment namespace.
         * @description Use this instead of the older endpoints,
         *
         *      - GET /v1/billing/active_subscription (legacy, for FakeYou)
         *      - GET /v1/app_state (quite a lot of FakeYou state)
         */
        get: operations["get_session_subscription_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The primary key for Audit Logs. */
        BatchGenerationToken: string;
        BatchGetInferenceJobStatusSuccessResponse: {
            job_states: components["schemas"]["BatchInferenceJobStatusResponsePayload"][];
            success: boolean;
        };
        BatchInferenceJobStatusResponsePayload: {
            /** Format: date-time */
            created_at: string;
            job_token: components["schemas"]["InferenceJobToken"];
            maybe_result?: null | components["schemas"]["BatchResultDetailsResponse"];
            request: components["schemas"]["BatchRequestDetailsResponse"];
            status: components["schemas"]["BatchStatusDetailsResponse"];
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Details about what the user requested for generation */
        BatchRequestDetailsResponse: {
            inference_category: components["schemas"]["InferenceCategory"];
            maybe_lipsync_details?: null | components["schemas"]["JobDetailsLipsyncRequest"];
            maybe_live_portrait_details?: null | components["schemas"]["JobDetailsLivePortraitRequest"];
            /** @description OPTIONAL. Title of the model, if it has one */
            maybe_model_title?: string | null;
            maybe_model_token?: string | null;
            maybe_model_type?: string | null;
            maybe_prompt_token?: null | components["schemas"]["PromptToken"];
            /** @description OPTIONAL. If the result was TTS, this is the raw inference text. */
            maybe_raw_inference_text?: string | null;
            maybe_style_name?: null | components["schemas"]["StyleTransferName"];
        };
        /** @description Details about the completed result (if any) */
        BatchResultDetailsResponse: {
            entity_token: string;
            entity_type: string;
            /**
             * @deprecated
             * @description (DEPRECATED) URL path to the media file
             */
            maybe_public_bucket_media_path?: string | null;
            /** Format: date-time */
            maybe_successfully_completed_at?: string | null;
            /** @description Rich CDN links to the media, including thumbnails, previews, and more. */
            media_links: components["schemas"]["MediaLinks"];
        };
        /** @description Details about the ongoing job status */
        BatchStatusDetailsResponse: {
            /** Format: int32 */
            attempt_count: number;
            maybe_assigned_cluster?: string | null;
            maybe_assigned_worker?: string | null;
            /**
             * @description Extra, temporary status from Redis.
             *     This can denote inference progress, and the Python code can write to it.
             */
            maybe_extra_status_description?: string | null;
            maybe_failure_category?: null | components["schemas"]["FrontendFailureCategory"];
            /** Format: date-time */
            maybe_first_started_at?: string | null;
            /**
             * Format: int32
             * @description This is an integer number between 0 and 100 (both inclusive) that
             *     reports the completeness.
             */
            progress_percentage: number;
            /**
             * @description Whether the frontend needs to maintain a keepalive check.
             *     This is typically only for non-premium users.
             */
            requires_keepalive: boolean;
            /** @description Primary status from the database (a state machine). */
            status: components["schemas"]["JobStatusPlus"];
        };
        /** @description The primary key for Characters */
        CharacterToken: string;
        /**
         * @description Common aspect ratios for image and video generation.
         *
         *     NB: Keep the max serialized length to 24 characters.
         * @enum {string}
         */
        CommonAspectRatio: "auto" | "square" | "wide_three_by_two" | "wide_four_by_three" | "wide_five_by_four" | "wide_sixteen_by_nine" | "wide_twenty_one_by_nine" | "tall_two_by_three" | "tall_three_by_four" | "tall_four_by_five" | "tall_nine_by_sixteen" | "tall_nine_by_twenty_one" | "wide" | "tall" | "auto_2k" | "auto_3k" | "auto_4k" | "square_hd";
        /**
         * @description Audio models available for generation.
         * @enum {string}
         */
        CommonAudioModel: "suno_music" | "suno_remix" | "suno_sounds" | "suno_sample" | "seed_audio_1p0";
        /**
         * @description Common output bitrate levels for generation.
         *
         *     Most models default to `Normal`; `High` requests a higher bitrate where the
         *     model supports it. Models that don't support it simply ignore the value.
         *
         *     NB: Keep the max serialized length to 16 characters.
         * @enum {string}
         */
        CommonBitrate: "normal" | "high";
        /**
         * @description Image models available for generation.
         *     Mirrors artcraft_router::api::router_image_model::RouterImageModel.
         * @enum {string}
         */
        CommonImageModel: "flux_1_dev" | "flux_1_schnell" | "flux_pro_1p1" | "flux_pro_1p1_ultra" | "gpt_image_1" | "gpt_image_1p5" | "gpt_image_2" | "grok_imagine_image" | "grok_imagine_image_q" | "midjourney_7" | "midjourney_7_niji" | "midjourney_8" | "nano_banana" | "nano_banana_2" | "nano_banana_pro" | "seedream_4" | "seedream_4p5" | "seedream_5_lite" | "seedream_5p0_pro" | "seedream_5p0_pro_u" | "qwen_edit_2511_angles" | "flux_2_lora_angles";
        /**
         * @description Mesh (3D object) models available for generation.
         * @enum {string}
         */
        CommonMeshModel: "hunyuan_3d_2p0" | "hunyuan_3d_2p1" | "hunyuan_3d_3" | "hunyuan_3d_3_sketch" | "hunyuan_3d_3p1_pro" | "hunyuan_3d_3p1_rapid" | "hunyuan_3d_3p1_part" | "hunyuan_3d_3p1_topology" | "tripo3d_h3p1" | "meshy_v6" | "rodin_2p5_fast";
        /**
         * @description Mesh output types for 3D object generation.
         * @enum {string}
         */
        CommonMeshOutputType: "normal" | "low_poly" | "geometry";
        /**
         * @description Quality level for a mesh generation sub-feature (e.g. texture quality or
         *     geometry quality). Some models charge extra for `Detailed`.
         * @enum {string}
         */
        CommonMeshQuality: "standard" | "detailed";
        /**
         * @description Musical keys available for audio generation (eg. Suno Sounds).
         *
         *     NB: There are intentionally no E keys, per product spec.
         * @enum {string}
         */
        CommonMusicalKey: "auto" | "c_major" | "c_minor" | "d_major" | "d_minor" | "f_major" | "f_minor" | "g_major" | "g_minor" | "a_major" | "a_minor" | "b_major" | "b_minor";
        /**
         * @description Polygon types for generated meshes.
         * @enum {string}
         */
        CommonPolygonType: "triangle" | "quad";
        /**
         * @description Common quality levels for generation.
         *
         *     NB: Keep the max serialized length to 16 characters.
         * @enum {string}
         */
        CommonQuality: "high" | "medium" | "low";
        /**
         * @description Common resolutions for generation.
         *
         *     NB: Keep the max serialized length to 16 characters.
         * @enum {string}
         */
        CommonResolution: "one_k" | "two_k" | "three_k" | "four_k" | "half_k" | "four_eighty_p" | "seven_twenty_p" | "ten_eighty_p";
        /**
         * @description Splat models available for generation.
         * @enum {string}
         */
        CommonSplatModel: "marble_0p1_mini" | "marble_0p1_plus" | "marble_1p0" | "marble_1p0_draft" | "marble_1p1" | "marble_1p1_plus" | "triposplat";
        /**
         * @description Video models available for generation.
         *     Mirrors artcraft_router::api::router_video_model::RouterVideoModel.
         * @enum {string}
         */
        CommonVideoModel: "grok_video" | "grok_imagine_video" | "grok_imagine_video_1p5" | "flux_3" | "flux_3_draft" | "kling_1p6_pro" | "kling_2p1_pro" | "kling_2p1_master" | "kling_2p5_turbo_pro" | "kling_2p6_pro" | "kling_3p0_standard" | "kling_3p0_pro" | "happy_horse_1p0" | "minimax_h3" | "minimax_h3_turbo" | "minimax_h3_ultra" | "seedance_1p0_lite" | "seedance_1p5_pro" | "seedance_2p0" | "seedance_2p0_fast" | "seedance_2p0_bp" | "seedance_2p0_bp_fast" | "seedance_2p0_u" | "seedance_2p0_u_fast" | "seedance_2p0_bpu" | "seedance_2p0_bpu_fast" | "seedance_2p0_mini" | "seedance_2p0_bp_mini" | "seedance_2p0_bpu_mini" | "seedance_2p5_preview" | "seedance_2p5" | "seedance_2p5_u" | "sora_2" | "sora_2_pro" | "veo_2" | "veo_3" | "veo_3_fast" | "veo_3p1" | "veo_3p1_fast" | "veo_3p1_lite" | "vidu_q3" | "vidu_q3_turbo" | "preview_model" | "preview_model_fast";
        CommonWebError: {
            /** Format: int32 */
            error_code: number;
            error_code_str?: string;
            /** @description User-facing error message (present only for bad input errors) */
            message?: string;
            success: boolean;
        };
        /**
         * @description These fields are ignored by generation. They're only used by the frontend
         *     to aid in cost estimation (e.g. Seedance 2.5 bills reference-video input
         *     seconds, so the cost quote needs the combined input duration without the
         *     server downloading and probing the files on every poll).
         */
        EstimateFields: {
            /**
             * Format: int32
             * @description Combined duration of all reference audio inputs, in milliseconds.
             *     (No model bills audio input seconds yet; accepted for future models.)
             */
            total_input_audio_duration_millis?: number | null;
            /**
             * Format: int32
             * @description Combined duration of all reference video inputs, in milliseconds.
             */
            total_input_video_duration_millis?: number | null;
        };
        /** @enum {string} */
        FakeYouPlan: "free" | "basic" | "standard" | "pro";
        /**
         * @description Used in the `generic_inference_jobs` table in `VARCHAR(32)` field `frontend_failure_category`.
         *
         *     When jobs fail (permanently or transiently), we need to inform the frontend of the reason,
         *     because perhaps there's something the user can do to change their input.
         *
         *     The previous "VARCHAR(32) failure_reason" column was a text-based message that could not be
         *     localized or made user friendly. This `frontend_failure_category` exists to provide well-defined
         *     failure categories to the frontend that can easily be localized and indicated consistently in
         *     the UI.
         *
         *     Another benefit is that we'll surface all of the various types of failure and perhaps eventually
         *     come to handle some in a cross-cutting way.
         *
         *     YOU CAN ADD NEW VALUES, BUT DO NOT CHANGE EXISTING VALUES WITHOUT A MIGRATION STRATEGY.
         * @enum {string}
         */
        FrontendFailureCategory: "face_not_detected" | "no_foreground_subject_detected" | "format_not_supported" | "keep_alive_elapsed" | "not_yet_implemented" | "retryable_worker_error" | "model_rules_violation" | "rule_bans_user_image" | "rule_bans_user_image_with_faces" | "rule_bans_user_text_prompt" | "rule_bans_user_content" | "rule_bans_generated_video" | "rule_bans_generated_audio" | "rule_bans_generated_content" | "filesize_too_large" | "image_dimensions_too_small" | "image_dimensions_too_large" | "generation_failed";
        /**
         * @description A forward-compatible version of `FrontendFailureCategory` for API clients.
         *
         *     Contains all known variants plus an `Unknown(String)` catch-all so that
         *     newer server-side values never cause deserialization failures on the client.
         */
        FrontendFailureCategoryForApiClients: "face_not_detected" | "no_foreground_subject_detected" | "format_not_supported" | "keep_alive_elapsed" | "not_yet_implemented" | "retryable_worker_error" | "model_rules_violation" | "rule_bans_user_image" | "rule_bans_user_image_with_faces" | "rule_bans_user_text_prompt" | "rule_bans_user_content" | "rule_bans_generated_video" | "rule_bans_generated_audio" | "rule_bans_generated_content" | "filesize_too_large" | "image_dimensions_too_small" | "image_dimensions_too_large" | "generation_failed" | {
            /**
             * @description Catch-all for values the client doesn't yet know about.
             *     The contained string is the raw serialized value from the server.
             */
            unknown: string;
        };
        /**
         * @description A restricted subset of `FrontendFailureCategory` that only includes values
         *     known to old deployed clients. New failure categories are omitted so that
         *     old clients never receive an enum value they cannot deserialize.
         * @enum {string}
         */
        FrontendFailureCategoryForOldClients: "face_not_detected" | "keep_alive_elapsed" | "not_yet_implemented" | "retryable_worker_error";
        /**
         * @description NB: This will be used by a variety of tables (MySQL and sqlite)!
         *     Keep the max length to 16 characters.
         * @enum {string}
         */
        GenerationProvider: "artcraft" | "fal" | "grok" | "midjourney" | "sora" | "world_labs";
        /** @description For the URL PathInfo */
        GetInferenceJobStatusPathInfo: {
            token: components["schemas"]["InferenceJobToken"];
        };
        GetInferenceJobStatusSuccessResponse: {
            state: components["schemas"]["InferenceJobStatusResponsePayload"];
            success: boolean;
        };
        /** @description For the URL PathInfo */
        GetSessionCreditsPathInfo: {
            namespace: components["schemas"]["PaymentsNamespace"];
        };
        GetSessionCreditsResponse: {
            /**
             * Format: int64
             * @description Any banked credits the user might have.
             */
            banked_credits: number;
            /**
             * Format: int64
             * @description Any free credits the user might have
             *     We might support daily free credits.
             */
            free_credits: number;
            /**
             * Format: int64
             * @description Any monthly refilling credits the user might have
             */
            monthly_credits: number;
            success: boolean;
            /**
             * Format: int64
             * @description All the credit amounts added together.
             */
            sum_total_credits: number;
        };
        /** @description For the URL PathInfo */
        GetSessionSubscriptionPathInfo: {
            namespace: components["schemas"]["PaymentsNamespace"];
        };
        GetSessionSubscriptionResponse: {
            active_subscription?: null | components["schemas"]["SubscriptionInfo"];
            success: boolean;
        };
        GoogleCreateAccountRequest: {
            google_credential: string;
            /**
             * @description Optional: The URL where the user landed when they first arrived.
             *     The browser can send `window.location.href`.
             */
            maybe_landing_url?: string | null;
            /**
             * @description Optional: A referral code created by another user. If present, takes priority over
             *     `maybe_referral_username` for resolving the referring user.
             */
            maybe_referral_code?: string | null;
            /**
             * @description Optional: The referral URL the user arrived from when first hitting the site.
             *     The browser can send `document.referrer` to the backend.
             *     If not provided, we'll try the `referer` header.
             */
            maybe_referral_url?: string | null;
            /** @description Optional: A referral username or code from a referring user. */
            maybe_referral_username?: string | null;
        };
        GoogleCreateAccountSuccessResponse: {
            /**
             * @description The user's display username. If we want to present a username
             *     customization flow, we can use this to prevent another round trip.
             */
            maybe_user_display_name?: string | null;
            /**
             * @description A signed session that can be sent as a header, bypassing cookies.
             *     This is useful for API clients that don't support cookies or Google
             *     browsers killing cross-domain cookies.
             */
            signed_session: string;
            success: boolean;
            /**
             * @description If the username was automatically generated and not yet customized,
             *     this will report true. We should show the user a dialogue to change
             *     their username.
             */
            username_not_yet_customized: boolean;
        };
        /**
         * @description Used in the `generic_inference_jobs` table in `VARCHAR(32)` field `inference_category`.
         *
         *     Our "generic inference" pipeline supports a wide variety of ML models and other media.
         *     Each "category" of inference is identified by the following enum variants.
         *     These types are present in the HTTP API and database columns as serialized here.
         *
         *     YOU CAN ADD NEW VALUES, BUT DO NOT CHANGE EXISTING VALUES WITHOUT A MIGRATION STRATEGY.
         * @enum {string}
         */
        InferenceCategory: "deprecated_field" | "lipsync_animation" | "text_to_speech" | "voice_conversion" | "image_generation" | "video_generation" | "audio_generation" | "object_generation" | "splat_generation" | "character_generation" | "background_removal" | "mocap" | "workflow" | "format_conversion" | "live_portrait" | "seed_vc" | "video_filter" | "convert_bvh_to_workflow" | "f5_tts";
        InferenceJobStatusResponsePayload: {
            /** Format: date-time */
            created_at: string;
            job_token: components["schemas"]["InferenceJobToken"];
            maybe_result?: null | components["schemas"]["ResultDetailsResponse"];
            request: components["schemas"]["RequestDetailsResponse"];
            status: components["schemas"]["StatusDetailsResponse"];
            /** Format: date-time */
            updated_at: string;
        };
        /** @description The primary key for "generic" inference jobs. */
        InferenceJobToken: string;
        /** @description Details about submitted lipsync jobs (request arguments only) */
        JobDetailsLipsyncRequest: {
            /**
             * @description Media file token for the source audio.
             *     This is probably an audio file, but in the future we might pull audio from video.
             */
            audio_source_token: components["schemas"]["MediaFileToken"];
            /**
             * @description Media file token for the source visuals.
             *     This is either an image or video.
             */
            image_or_video_source_token: components["schemas"]["MediaFileToken"];
        };
        /** @description Details about submitted live portrait jobs (request arguments only) */
        JobDetailsLivePortraitRequest: {
            /**
             * @description Driving media token
             *     This must be a video media file token.
             *     This drives the animation of the face, but the actor will disappear
             *     and their facial expressions will be transferred to the source.
             *     This video must contain a face.
             */
            face_driver_media_file_token: components["schemas"]["MediaFileToken"];
            /**
             * @description Source media token
             *     This can be an image or a video media file token
             *     This is what constitutes the "portrait" or the overall final video.
             *     This video or image must contain a face.
             */
            source_media_file_token: components["schemas"]["MediaFileToken"];
        };
        /**
         * @description This is used in newer jobs (that add additional enum states)
         *
         *      - generic_inference_job
         *      - (no other jobs yet)
         *
         *     See the documentation on the table for usage.
         *
         *     DO NOT CHANGE VALUES WITHOUT A MIGRATION STRATEGY.
         * @enum {string}
         */
        JobStatusPlus: "pending" | "started" | "complete_success" | "complete_failure" | "attempt_failed" | "dead" | "cancelled_by_user" | "cancelled_by_system";
        ListSessionJobsItem: {
            /** Format: date-time */
            created_at: string;
            job_token: components["schemas"]["InferenceJobToken"];
            maybe_result?: null | components["schemas"]["ListSessionResultDetailsResponse"];
            request: components["schemas"]["ListSessionRequestDetailsResponse"];
            status: components["schemas"]["ListSessionStatusDetailsResponse"];
            /** Format: date-time */
            updated_at: string;
        };
        ListSessionJobsSuccessResponse: {
            /** @description This is not paginated and is limited to showing 100 jobs. */
            jobs: components["schemas"]["ListSessionJobsItem"][];
            success: boolean;
        };
        /** @description Details about what the user requested for generation */
        ListSessionRequestDetailsResponse: {
            inference_category: components["schemas"]["InferenceCategory"];
            maybe_lipsync_details?: null | components["schemas"]["JobDetailsLipsyncRequest"];
            maybe_live_portrait_details?: null | components["schemas"]["JobDetailsLivePortraitRequest"];
            /** @description OPTIONAL. Title of the model, if it has one */
            maybe_model_title?: string | null;
            maybe_model_token?: string | null;
            maybe_model_type?: string | null;
            maybe_prompt_token?: null | components["schemas"]["PromptToken"];
            /** @description OPTIONAL. If the result was TTS, this is the raw inference text. */
            maybe_raw_inference_text?: string | null;
            maybe_style_name?: null | components["schemas"]["StyleTransferName"];
        };
        /** @description Details about the completed result (if any) */
        ListSessionResultDetailsResponse: {
            entity_token: string;
            entity_type: string;
            maybe_batch_token?: null | components["schemas"]["BatchGenerationToken"];
            /**
             * @deprecated
             * @description (DEPRECATED) URL path to the media file
             */
            maybe_public_bucket_media_path?: string | null;
            /** Format: date-time */
            maybe_successfully_completed_at?: string | null;
            /** @description Rich CDN links to the media, including thumbnails, previews, and more. */
            media_links: components["schemas"]["MediaLinks"];
        };
        /** @description Details about the ongoing job status */
        ListSessionStatusDetailsResponse: {
            /** Format: int32 */
            attempt_count: number;
            maybe_assigned_cluster?: string | null;
            maybe_assigned_worker?: string | null;
            /**
             * Format: int64
             * @description If the job is currently running, this is how long it has been running in seconds.
             *     This is heuristic estimate since we don't record the precise start time across runs.
             */
            maybe_current_execution_duration_seconds?: number | null;
            /**
             * @description Extra, temporary status from Redis.
             *     This can denote inference progress, and the Python code can write to it.
             */
            maybe_extra_status_description?: string | null;
            maybe_failure_category?: null | components["schemas"]["FrontendFailureCategoryForOldClients"];
            maybe_failure_category_updated?: null | components["schemas"]["FrontendFailureCategoryForApiClients"];
            /** @description User-facing failure messages */
            maybe_failure_message?: string | null;
            /** Format: date-time */
            maybe_first_started_at?: string | null;
            /**
             * Format: int32
             * @description This is an integer number between 0 and 100 (both inclusive) that
             *     reports the completeness.
             */
            progress_percentage: number;
            /**
             * @description Whether the frontend needs to maintain a keepalive check.
             *     This is typically only for non-premium users.
             */
            requires_keepalive: boolean;
            /** @description Primary status from the database (a state machine). */
            status: components["schemas"]["JobStatusPlus"];
        };
        LoginErrorResponse: {
            error_message: string;
            error_type: components["schemas"]["LoginErrorType"];
            success: boolean;
        };
        /** @enum {string} */
        LoginErrorType: "AccountNeedsPassword" | "InvalidCredentials" | "ServerError";
        LoginRequest: {
            password: string;
            username_or_email: string;
        };
        LoginSuccessResponse: {
            /**
             * @description A signed session that can be sent as a header, bypassing cookies.
             *     This is useful for API clients that don't support cookies or Google
             *     browsers killing cross-domain cookies.
             */
            signed_session: string;
            success: boolean;
        };
        LogoutSuccessResponse: {
            success: boolean;
        };
        /** @description The primary key for Media Files */
        MediaFileToken: string;
        /** @description Links to media file locations (bucket, CDN, etc.) */
        MediaLinks: {
            /**
             * Format: uri
             * @description Primary link to the asset via the CDN.
             */
            cdn_url: string;
            /**
             * @description Template to construct thumbnail URLs.
             *     Replace the string `{WIDTH}` with the desired width.
             *     Only relevant for image media files. (Video media files instead have
             *     video previews, which, in turn, have their own thumbnail templates.)
             */
            maybe_thumbnail_template?: string | null;
            maybe_video_previews?: null | components["schemas"]["VideoPreviews"];
        };
        /**
         * @description The company or organization that created a model.
         * @enum {string}
         */
        ModelCreator: "alibaba" | "artcraft" | "black_forest_labs" | "bytedance" | "deemos" | "fal" | "google" | "grok" | "hailuo" | "higgsfield" | "kling" | "krea" | "meshy" | "midjourney" | "open_ai" | "open_art" | "recraft" | "replicate" | "runway" | "stability" | "suno" | "tencent" | "tensor_art" | "tripo" | "vidu" | "world_labs";
        /** @description Shared request body for both the audio cost estimate and audio generation endpoints. */
        OmniGenAudioCostAndGenerateRequest: {
            /**
             * @description Reference audio (optional).
             *     The remix/sample source, or Seed Audio @Audio references (up to 3).
             */
            audio_media_tokens?: components["schemas"]["MediaFileToken"][] | null;
            /**
             * Format: int32
             * @description Beats per minute (Suno Sounds).
             */
            bpm?: number | null;
            /**
             * @description REQUIRED (even if marked optional)
             *     Idempotency token to prevent duplicate requests.
             */
            idempotency_token?: string | null;
            /**
             * @description Reference image (optional).
             *     Seed Audio supports a single reference image; cannot be combined with audio references.
             */
            image_media_tokens?: components["schemas"]["MediaFileToken"][] | null;
            /** @description Whether to generate instrumental-only audio (Suno Music / Sample). */
            is_instrumental?: boolean | null;
            /** @description Whether the sound should loop vs a single hit (Suno Sounds). */
            is_loopable?: boolean | null;
            /** @description Whether to keep the original lyrics (Suno Remix). */
            keep_lyrics?: boolean | null;
            model?: null | components["schemas"]["CommonAudioModel"];
            musical_key?: null | components["schemas"]["CommonMusicalKey"];
            /**
             * Format: double
             * @description Pitch shift in semitones (Seed Audio: -12..=12).
             */
            pitch?: number | null;
            /** @description The text prompt for the audio generation. */
            prompt?: string | null;
            /**
             * Format: int32
             * @description Output sample rate in Hz (Seed Audio: 8000/16000/24000/32000/44100/48000).
             */
            sample_rate_hz?: number | null;
            /**
             * Format: double
             * @description Playback speed multiplier (Seed Audio: 0.5–2.0).
             */
            speed?: number | null;
            /** @description Style/genre direction (Suno's "tags"). */
            style_prompt?: string | null;
            /**
             * Format: double
             * @description Volume multiplier (Seed Audio: 0.5–2.0).
             */
            volume?: number | null;
        };
        /** @description Response body for the omni-gen audio cost estimate endpoint. */
        OmniGenAudioCostResponse: {
            /**
             * Format: int64
             * @description Estimated cost in credits.
             */
            cost_in_credits?: number | null;
            /**
             * Format: int64
             * @description Estimated cost in USD cents.
             */
            cost_in_usd_cents?: number | null;
            /**
             * @description Whether failures are refunded.
             *     True: 100% yes
             *     False: 100% no
             *     None: Unknown or variable
             */
            failures_are_refunded?: boolean | null;
            /** @description Whether the output will have a watermark. */
            has_watermark: boolean;
            /** @description Whether the generation is free for this user/plan. */
            is_free: boolean;
            /** @description Whether the user is rate-limited. */
            is_rate_limited: boolean;
            /** @description Whether the user has unlimited generations. */
            is_unlimited: boolean;
            success: boolean;
        };
        OmniGenAudioModelDetails: {
            /** Format: int32 */
            audio_references_max?: number | null;
            audio_references_supported?: boolean | null;
            bpm_supported?: boolean | null;
            /** @description Additional details about the model. */
            extra_info?: string | null;
            /** @description Additional details about the model. (Brief; only a few words.) */
            extra_info_short?: string | null;
            full_name?: string | null;
            /** Format: int32 */
            image_references_max?: number | null;
            image_references_supported?: boolean | null;
            /** @description Whether the instrumental-only toggle is supported (Suno Music / Sample). */
            instrumental_toggle_supported?: boolean | null;
            is_disabled?: boolean | null;
            /** @description Whether the "keep lyrics" toggle is supported (Suno Remix). */
            keep_lyrics_supported?: boolean | null;
            /** @description Whether the loop vs single-hit toggle is supported (Suno Sounds). */
            loopable_toggle_supported?: boolean | null;
            model: components["schemas"]["CommonAudioModel"];
            model_creator?: null | components["schemas"]["ModelCreator"];
            musical_key_supported?: boolean | null;
            pitch_supported?: boolean | null;
            /** Format: int32 */
            sample_rate_hz_default?: number | null;
            sample_rate_hz_options?: number[] | null;
            speed_supported?: boolean | null;
            /** @description Whether a style/genre prompt (Suno's "tags") is supported. */
            style_prompt_supported?: boolean | null;
            text_prompt_supported?: boolean | null;
            volume_supported?: boolean | null;
        };
        OmniGenAudioModelProviderDetails: {
            models: components["schemas"]["OmniGenAudioProviderModelDetails"][];
            provider: components["schemas"]["GenerationProvider"];
        };
        /** @description Response body for the audio models endpoint. */
        OmniGenAudioModelsResponse: {
            /** @description A list of all models: details, features, and capabilities */
            models: components["schemas"]["OmniGenAudioModelDetails"][];
            /**
             * @description Provider-by-provider model offering and capability list,
             *     with possible capability overrides (future)
             */
            providers: components["schemas"]["OmniGenAudioModelProviderDetails"][];
            success: boolean;
        };
        OmniGenAudioProviderModelDetails: {
            model: components["schemas"]["CommonAudioModel"];
            overrides?: null | components["schemas"]["OmniGenAudioModelDetails"];
        };
        /** @description Shared request body for both the image cost estimate and image generation endpoints. */
        OmniGenImageCostAndGenerateRequest: {
            /**
             * Format: double
             * @description Only for angle manipulation models.
             */
            adjust_horizontal_angle?: number | null;
            /**
             * Format: double
             * @description Only for angle manipulation models.
             */
            adjust_vertical_angle?: number | null;
            /**
             * Format: double
             * @description Only for angle manipulation models.
             */
            adjust_zoom?: number | null;
            aspect_ratio?: null | components["schemas"]["CommonAspectRatio"];
            /**
             * @description REQUIRED (even if marked optional)
             *     Idempotency token to prevent duplicate requests.
             *     If not supplied, we'll generate one for the required providers.
             */
            idempotency_token?: string | null;
            /**
             * Format: int32
             * @description How many images to generate.
             */
            image_batch_count?: number | null;
            /**
             * @description Input images for image editing.
             *     If present, we're doing image editing (image-to-image).
             *     If absent, we're doing text-to-image.
             */
            image_media_tokens?: components["schemas"]["MediaFileToken"][] | null;
            model?: null | components["schemas"]["CommonImageModel"];
            /** @description The prompt for the image generation. */
            prompt?: string | null;
            quality?: null | components["schemas"]["CommonQuality"];
            resolution?: null | components["schemas"]["CommonResolution"];
        };
        /** @description Response body for the omni-gen image cost estimate endpoint. */
        OmniGenImageCostResponse: {
            /**
             * Format: int64
             * @description Estimated cost in credits.
             */
            cost_in_credits?: number | null;
            /**
             * Format: int64
             * @description Estimated cost in USD cents.
             */
            cost_in_usd_cents?: number | null;
            /**
             * @description Whether failures are refunded.
             *     True: 100% yes
             *     False: 100% no
             *     None: Unknown or variable
             */
            failures_are_refunded?: boolean | null;
            /** @description Whether the output will have a watermark. */
            has_watermark: boolean;
            /** @description Whether the generation is free for this user/plan. */
            is_free: boolean;
            /** @description Whether the user is rate limited. */
            is_rate_limited: boolean;
            /** @description Whether the user has unlimited generations. */
            is_unlimited: boolean;
            success: boolean;
        };
        OmniGenImageModelDetails: {
            aspect_ratio_default?: null | components["schemas"]["CommonAspectRatio"];
            aspect_ratio_default_when_editing?: null | components["schemas"]["CommonAspectRatio"];
            aspect_ratio_options?: components["schemas"]["CommonAspectRatio"][] | null;
            /** Format: int32 */
            batch_size_default?: number | null;
            /** Format: int32 */
            batch_size_max?: number | null;
            /** Format: int32 */
            batch_size_min?: number | null;
            batch_size_options?: number[] | null;
            default_quality?: null | components["schemas"]["CommonQuality"];
            full_name?: string | null;
            has_fixed_editing_aspect_ratio?: boolean | null;
            /** Format: int32 */
            image_refs_max?: number | null;
            image_refs_supported?: boolean | null;
            is_disabled?: boolean | null;
            model: components["schemas"]["CommonImageModel"];
            model_creator?: null | components["schemas"]["ModelCreator"];
            /** Format: int32 */
            negative_text_prompt_max_length?: number | null;
            negative_text_prompt_supported?: boolean | null;
            quality_options?: components["schemas"]["CommonQuality"][] | null;
            resolution_default?: null | components["schemas"]["CommonResolution"];
            resolution_options?: components["schemas"]["CommonResolution"][] | null;
            /** Format: int32 */
            text_prompt_max_length?: number | null;
            text_prompt_supported?: boolean | null;
        };
        OmniGenImageModelProviderDetails: {
            models: components["schemas"]["OmniGenImageProviderModelDetails"][];
            provider: components["schemas"]["GenerationProvider"];
        };
        /**
         * @description The provider filter for the models endpoint.
         * @enum {string}
         */
        OmniGenImageModelsProvider: "artcraft" | "all";
        /**
         * @description Response body for the image models endpoint.
         *     TBD — fields will be added later.
         */
        OmniGenImageModelsResponse: {
            models: components["schemas"]["OmniGenImageModelDetails"][];
            providers: components["schemas"]["OmniGenImageModelProviderDetails"][];
            success: boolean;
        };
        OmniGenImageProviderModelDetails: {
            model: components["schemas"]["CommonImageModel"];
            overrides?: null | components["schemas"]["OmniGenImageModelDetails"];
        };
        /** @description Shared request body for both the mesh cost estimate and mesh generation endpoints. */
        OmniGenMeshCostAndGenerateRequest: {
            back_image_media_token?: null | components["schemas"]["MediaFileToken"];
            /** @description Whether to generate PBR (physically based rendering) materials. */
            enable_pbr?: boolean | null;
            /**
             * @description Whether to generate textures. Some models (Tripo3D) can skip texturing
             *     for a cheaper, faster generation.
             */
            enable_texture?: boolean | null;
            /**
             * Format: int64
             * @description Target face count for the generated mesh.
             */
            face_count?: number | null;
            front_image_media_token?: null | components["schemas"]["MediaFileToken"];
            geometry_quality?: null | components["schemas"]["CommonMeshQuality"];
            /**
             * @description REQUIRED (even if marked optional)
             *     Idempotency token to prevent duplicate requests.
             */
            idempotency_token?: string | null;
            input_mesh_media_token?: null | components["schemas"]["MediaFileToken"];
            left_image_media_token?: null | components["schemas"]["MediaFileToken"];
            mesh_output_type?: null | components["schemas"]["CommonMeshOutputType"];
            model?: null | components["schemas"]["CommonMeshModel"];
            polygon_type?: null | components["schemas"]["CommonPolygonType"];
            /** @description The text prompt for the mesh generation (text-to-3D). */
            prompt?: string | null;
            /**
             * @description Reference images (optional).
             *     The primary/front input image, or the sketch image for sketch-to-3D.
             */
            reference_image_media_tokens?: components["schemas"]["MediaFileToken"][] | null;
            right_image_media_token?: null | components["schemas"]["MediaFileToken"];
            texture_quality?: null | components["schemas"]["CommonMeshQuality"];
        };
        /** @description Response body for the omni-gen mesh cost estimate endpoint. */
        OmniGenMeshCostResponse: {
            /**
             * Format: int64
             * @description Estimated cost in credits.
             */
            cost_in_credits?: number | null;
            /**
             * Format: int64
             * @description Estimated cost in USD cents.
             */
            cost_in_usd_cents?: number | null;
            /**
             * @description Whether failures are refunded.
             *     True: 100% yes
             *     False: 100% no
             *     None: Unknown or variable
             */
            failures_are_refunded?: boolean | null;
            /** @description Whether the output will have a watermark. */
            has_watermark: boolean;
            /** @description Whether the generation is free for this user/plan. */
            is_free: boolean;
            /** @description Whether the user is rate-limited. */
            is_rate_limited: boolean;
            /** @description Whether the user has unlimited generations. */
            is_unlimited: boolean;
            success: boolean;
        };
        OmniGenMeshModelDetails: {
            /** @description Additional details about the model. */
            extra_info?: string | null;
            /** @description Additional details about the model. (Brief; only a few words.) */
            extra_info_short?: string | null;
            /** @description Whether a target face count can be specified. */
            face_count_supported?: boolean | null;
            full_name?: string | null;
            /** @description Whether a geometry quality level (standard/detailed) can be selected. */
            geometry_quality_supported?: boolean | null;
            /** @description Whether image-to-3D input is supported. */
            image_input_supported?: boolean | null;
            is_disabled?: boolean | null;
            /**
             * @description Whether the model takes an existing mesh file as input
             *     (mesh-to-mesh models like part splitting and retopology).
             */
            mesh_input_supported?: boolean | null;
            /** @description The mesh output types the model supports. */
            mesh_output_types?: components["schemas"]["CommonMeshOutputType"][] | null;
            model: components["schemas"]["CommonMeshModel"];
            model_creator?: null | components["schemas"]["ModelCreator"];
            /** @description Whether multi-view (front/back/left/right) image input is supported. */
            multi_view_supported?: boolean | null;
            /** @description Whether PBR (physically based rendering) material generation is supported. */
            pbr_supported?: boolean | null;
            /** @description The polygon types the model supports. */
            polygon_types?: components["schemas"]["CommonPolygonType"][] | null;
            /** @description Whether sketch-to-3D input is supported. */
            sketch_input_supported?: boolean | null;
            /** @description Whether text-to-3D prompting is supported. */
            text_prompt_supported?: boolean | null;
            /** @description Whether a texture quality level (standard/detailed) can be selected. */
            texture_quality_supported?: boolean | null;
            /** @description Whether texture generation can be toggled off (untextured output). */
            texture_toggle_supported?: boolean | null;
        };
        OmniGenMeshModelProviderDetails: {
            models: components["schemas"]["OmniGenMeshProviderModelDetails"][];
            provider: components["schemas"]["GenerationProvider"];
        };
        /** @description Response body for the mesh models endpoint. */
        OmniGenMeshModelsResponse: {
            /** @description A list of all models: details, features, and capabilities */
            models: components["schemas"]["OmniGenMeshModelDetails"][];
            /**
             * @description Provider-by-provider model offering and capability list,
             *     with possible capability overrides (future)
             */
            providers: components["schemas"]["OmniGenMeshModelProviderDetails"][];
            success: boolean;
        };
        OmniGenMeshProviderModelDetails: {
            model: components["schemas"]["CommonMeshModel"];
            overrides?: null | components["schemas"]["OmniGenMeshModelDetails"];
        };
        /** @description Shared request body for both the splat cost estimate and splat generation endpoints. */
        OmniGenSplatCostAndGenerateRequest: {
            /** @description Whether to disable prompt recaptioning. */
            disable_recaption?: boolean | null;
            /**
             * @description REQUIRED (even if marked optional)
             *     Idempotency token to prevent duplicate requests.
             */
            idempotency_token?: string | null;
            /** @description Whether the single reference image is a 360-degree panorama. */
            is_panoramic?: boolean | null;
            model?: null | components["schemas"]["CommonSplatModel"];
            /** @description The text prompt for the splat generation. */
            prompt?: string | null;
            /**
             * @description Reference images (optional).
             *     NOTE: Spherical/panorama coordinates are not yet supported per-image;
             *     multiple images are treated as multi-view input of the same world.
             */
            reference_image_media_tokens?: components["schemas"]["MediaFileToken"][] | null;
            reference_video_media_token?: null | components["schemas"]["MediaFileToken"];
        };
        /** @description Response body for the omni-gen splat cost estimate endpoint. */
        OmniGenSplatCostResponse: {
            /**
             * Format: int64
             * @description Estimated cost in credits.
             */
            cost_in_credits?: number | null;
            /**
             * Format: int64
             * @description Estimated cost in USD cents.
             */
            cost_in_usd_cents?: number | null;
            /**
             * @description Whether failures are refunded.
             *     True: 100% yes
             *     False: 100% no
             *     None: Unknown or variable
             */
            failures_are_refunded?: boolean | null;
            /** @description Whether the output will have a watermark. */
            has_watermark: boolean;
            /** @description Whether the generation is free for this user/plan. */
            is_free: boolean;
            /** @description Whether the user is rate-limited. */
            is_rate_limited: boolean;
            /** @description Whether the user has unlimited generations. */
            is_unlimited: boolean;
            success: boolean;
        };
        OmniGenSplatModelDetails: {
            /** @description Whether the "disable recaption" toggle is supported. */
            disable_recaption_supported?: boolean | null;
            /** @description Additional details about the model. */
            extra_info?: string | null;
            /** @description Additional details about the model. (Brief; only a few words.) */
            extra_info_short?: string | null;
            full_name?: string | null;
            /** Format: int32 */
            image_references_max?: number | null;
            image_references_supported?: boolean | null;
            is_disabled?: boolean | null;
            model: components["schemas"]["CommonSplatModel"];
            model_creator?: null | components["schemas"]["ModelCreator"];
            /** @description Whether a 360-degree panorama reference image is supported. */
            panorama_supported?: boolean | null;
            text_prompt_supported?: boolean | null;
            /** @description Whether a reference video input is supported. */
            video_reference_supported?: boolean | null;
        };
        OmniGenSplatModelProviderDetails: {
            models: components["schemas"]["OmniGenSplatProviderModelDetails"][];
            provider: components["schemas"]["GenerationProvider"];
        };
        /** @description Response body for the splat models endpoint. */
        OmniGenSplatModelsResponse: {
            /** @description A list of all models: details, features, and capabilities */
            models: components["schemas"]["OmniGenSplatModelDetails"][];
            /**
             * @description Provider-by-provider model offering and capability list,
             *     with possible capability overrides (future)
             */
            providers: components["schemas"]["OmniGenSplatModelProviderDetails"][];
            success: boolean;
        };
        OmniGenSplatProviderModelDetails: {
            model: components["schemas"]["CommonSplatModel"];
            overrides?: null | components["schemas"]["OmniGenSplatModelDetails"];
        };
        /** @description Shared request body for both the video cost estimate and video generation endpoints. */
        OmniGenVideoCostAndGenerateRequest: {
            aspect_ratio?: null | components["schemas"]["CommonAspectRatio"];
            bitrate?: null | components["schemas"]["CommonBitrate"];
            /**
             * Format: int32
             * @description How many seconds to generate.
             */
            duration_seconds?: number | null;
            end_frame_image_media_token?: null | components["schemas"]["MediaFileToken"];
            estimate_only?: null | components["schemas"]["EstimateFields"];
            /**
             * @description Whether to turn on/off audio.
             *     Not all models support audio, not all models have a choice.
             *     Some models will default this to true, others will default it to false,
             *     so it's best to be explicit.
             */
            generate_audio?: boolean | null;
            /**
             * @description REQUIRED (even if marked optional)
             *     Idempotency token to prevent duplicate requests.
             */
            idempotency_token?: string | null;
            model?: null | components["schemas"]["CommonVideoModel"];
            /** @description Some models support negative text prompts. */
            negative_prompt?: string | null;
            /** @description The text prompt for the video generation. */
            prompt?: string | null;
            quality?: null | components["schemas"]["CommonQuality"];
            /** @description Reference audio (optional). */
            reference_audio_media_tokens?: components["schemas"]["MediaFileToken"][] | null;
            /**
             * @description Optional character tokens to reference in the prompt.
             *     Characters are referenced in prompts as @CharacterName.
             */
            reference_character_tokens?: components["schemas"]["CharacterToken"][] | null;
            /** @description Reference images (optional). */
            reference_image_media_tokens?: components["schemas"]["MediaFileToken"][] | null;
            /** @description Reference videos (optional). */
            reference_video_media_tokens?: components["schemas"]["MediaFileToken"][] | null;
            resolution?: null | components["schemas"]["CommonResolution"];
            start_frame_image_media_token?: null | components["schemas"]["MediaFileToken"];
            /**
             * Format: int32
             * @description How many videos to generate.
             */
            video_batch_count?: number | null;
        };
        /** @description Response body for the omni-gen video cost estimate endpoint. */
        OmniGenVideoCostResponse: {
            /**
             * Format: int64
             * @description Estimated cost in credits.
             */
            cost_in_credits?: number | null;
            /**
             * Format: int64
             * @description Estimated cost in USD cents.
             */
            cost_in_usd_cents?: number | null;
            /**
             * @description Whether failures are refunded.
             *     True: 100% yes
             *     False: 100% no
             *     None: Unknown or variable
             */
            failures_are_refunded?: boolean | null;
            /** @description Whether the output will have a watermark. */
            has_watermark: boolean;
            /** @description Whether the generation is free for this user/plan. */
            is_free: boolean;
            /** @description Whether the user is rate-limited. */
            is_rate_limited: boolean;
            /** @description Whether the user has unlimited generations. */
            is_unlimited: boolean;
            success: boolean;
        };
        OmniGenVideoModelDetails: {
            aspect_ratio_default?: null | components["schemas"]["CommonAspectRatio"];
            aspect_ratio_options?: components["schemas"]["CommonAspectRatio"][] | null;
            /** Format: int32 */
            audio_references_max?: number | null;
            /** Format: int32 */
            audio_references_max_total_duration_seconds?: number | null;
            audio_references_supported?: boolean | null;
            /** Format: int32 */
            batch_size_default?: number | null;
            /** Format: int32 */
            batch_size_max?: number | null;
            /** Format: int32 */
            batch_size_min?: number | null;
            batch_size_options?: number[] | null;
            bitrate_default?: null | components["schemas"]["CommonBitrate"];
            bitrate_options?: components["schemas"]["CommonBitrate"][] | null;
            /** Format: int32 */
            character_references_max?: number | null;
            character_references_supported?: boolean | null;
            default_quality?: null | components["schemas"]["CommonQuality"];
            /** Format: int32 */
            duration_seconds_default?: number | null;
            /** Format: int32 */
            duration_seconds_max?: number | null;
            /**
             * Format: int32
             * @description Specific maximum when image references are used,
             *     eg. Grok limits to 10 seconds in this mode.
             */
            duration_seconds_max_with_image_references?: number | null;
            /** Format: int32 */
            duration_seconds_min?: number | null;
            duration_seconds_options?: number[] | null;
            ending_keyframe_supported?: boolean | null;
            /** @description Additional details about the model. */
            extra_info?: string | null;
            /** @description Additional details about the model. (Brief; only a few words.) */
            extra_info_short?: string | null;
            full_name?: string | null;
            /** Format: int32 */
            image_references_max?: number | null;
            image_references_supported?: boolean | null;
            is_disabled?: boolean | null;
            model: components["schemas"]["CommonVideoModel"];
            model_creator?: null | components["schemas"]["ModelCreator"];
            /** Format: int32 */
            negative_text_prompt_max_length?: number | null;
            negative_text_prompt_supported?: boolean | null;
            quality_options?: components["schemas"]["CommonQuality"][] | null;
            resolution_default?: null | components["schemas"]["CommonResolution"];
            resolution_options?: components["schemas"]["CommonResolution"][] | null;
            show_generate_with_sound_toggle?: boolean | null;
            starting_keyframe_required?: boolean | null;
            starting_keyframe_supported?: boolean | null;
            /** Format: int32 */
            text_prompt_max_length?: number | null;
            text_prompt_supported?: boolean | null;
            /** @description Whether a pure text-to-video modality is supported */
            text_to_video_supported?: boolean | null;
            /** Format: int32 */
            video_references_max?: number | null;
            /** Format: int32 */
            video_references_max_total_duration_seconds?: number | null;
            video_references_supported?: boolean | null;
        };
        OmniGenVideoModelProviderDetails: {
            models: components["schemas"]["OmniGenVideoProviderModelDetails"][];
            provider: components["schemas"]["GenerationProvider"];
        };
        /**
         * @description The provider filter for the models endpoint.
         * @enum {string}
         */
        OmniGenVideoModelsProvider: "artcraft" | "all";
        /**
         * @description Response body for the video models endpoint.
         *     TBD — fields will be added later.
         */
        OmniGenVideoModelsResponse: {
            /** @description A list of all models: details, features, and capabilities */
            models: components["schemas"]["OmniGenVideoModelDetails"][];
            /**
             * @description Provider-by-provider model offering and capability list,
             *     with possible capability overrides (future)
             */
            providers: components["schemas"]["OmniGenVideoModelProviderDetails"][];
            success: boolean;
        };
        OmniGenVideoProviderModelDetails: {
            model: components["schemas"]["CommonVideoModel"];
            overrides?: null | components["schemas"]["OmniGenVideoModelDetails"];
        };
        /**
         * @description NB: This will be used by a variety of tables (MySQL and sqlite)!
         *     Keep the max length to 16 characters.
         * @enum {string}
         */
        PaymentsNamespace: "artcraft" | "fakeyou";
        /** @description The primary key for Prompts */
        PromptToken: string;
        /** @description Details about what the user requested for generation */
        RequestDetailsResponse: {
            inference_category: components["schemas"]["InferenceCategory"];
            maybe_lipsync_details?: null | components["schemas"]["JobDetailsLipsyncRequest"];
            maybe_live_portrait_details?: null | components["schemas"]["JobDetailsLivePortraitRequest"];
            /** @description OPTIONAL. Title of the model, if it has one */
            maybe_model_title?: string | null;
            maybe_model_token?: string | null;
            maybe_model_type?: string | null;
            maybe_prompt_token?: null | components["schemas"]["PromptToken"];
            /** @description OPTIONAL. If the result was TTS, this is the raw inference text. */
            maybe_raw_inference_text?: string | null;
            maybe_style_name?: null | components["schemas"]["StyleTransferName"];
        };
        /** @description Details about the completed result (if any) */
        ResultDetailsResponse: {
            entity_token: string;
            entity_type: string;
            /**
             * @deprecated
             * @description (DEPRECATED) URL path to the media file
             */
            maybe_public_bucket_media_path?: string | null;
            /** Format: date-time */
            maybe_successfully_completed_at?: string | null;
            /** @description Rich CDN links to the media, including thumbnails, previews, and more. */
            media_links: components["schemas"]["MediaLinks"];
        };
        SessionInfoSuccessResponse: {
            logged_in: boolean;
            success: boolean;
            user?: null | components["schemas"]["SessionUserInfo"];
        };
        SessionOnboardingState: {
            /** @description If true, the user hasn't confirmed their email. */
            email_not_confirmed: boolean;
            /** @description If true, the user hasn't set their email. */
            email_not_set: boolean;
            /** @description If true, the user hasn't set their password. */
            password_not_set: boolean;
            /** @description If true, the user hasn't set their username (the username they have is random). */
            username_not_customized: boolean;
        };
        SessionUserInfo: {
            /** @deprecated */
            can_access_studio: boolean;
            can_approve_w2l_templates: boolean;
            can_ban_users: boolean;
            can_delete_other_users_tts_models: boolean;
            can_delete_other_users_tts_results: boolean;
            can_delete_other_users_w2l_results: boolean;
            can_delete_other_users_w2l_templates: boolean;
            can_delete_own_account: boolean;
            can_delete_own_tts_models: boolean;
            can_delete_own_tts_results: boolean;
            can_delete_own_w2l_results: boolean;
            can_delete_own_w2l_templates: boolean;
            can_delete_users: boolean;
            can_edit_other_users_profiles: boolean;
            can_edit_other_users_tts_models: boolean;
            can_edit_other_users_w2l_templates: boolean;
            can_upload_tts_models: boolean;
            can_upload_w2l_templates: boolean;
            can_use_tts: boolean;
            can_use_w2l: boolean;
            core_info: components["schemas"]["UserDetailsLight"];
            display_name: string;
            email_gravatar_hash: string;
            fakeyou_plan: components["schemas"]["FakeYouPlan"];
            /**
             * @description Collection of feature / rollout flags
             *     This is the proper place to detect if a user has access to some rollout (non-paywall) feature.
             *     NB: The BTreeSet maintains order so React doesn't introduce re-render state bugs when order changes
             */
            maybe_feature_flags: components["schemas"]["UserFeatureFlag"][];
            onboarding: components["schemas"]["SessionOnboardingState"];
            storyteller_stream_plan: components["schemas"]["StorytellerStreamPlan"];
            user_token: components["schemas"]["UserToken"];
            username: string;
        };
        /** @description Details about the ongoing job status */
        StatusDetailsResponse: {
            /** Format: int32 */
            attempt_count: number;
            maybe_assigned_cluster?: string | null;
            maybe_assigned_worker?: string | null;
            /**
             * @description Extra, temporary status from Redis.
             *     This can denote inference progress, and the Python code can write to it.
             */
            maybe_extra_status_description?: string | null;
            maybe_failure_category?: null | components["schemas"]["FrontendFailureCategory"];
            /** Format: date-time */
            maybe_first_started_at?: string | null;
            /**
             * Format: int32
             * @description This is an integer number between 0 and 100 (both inclusive) that
             *     reports the completeness.
             */
            progress_percentage: number;
            /**
             * @description Whether the frontend needs to maintain a keepalive check.
             *     This is typically only for non-premium users.
             */
            requires_keepalive: boolean;
            /** @description Primary status from the database (a state machine). */
            status: components["schemas"]["JobStatusPlus"];
        };
        /** @enum {string} */
        StorytellerStreamPlan: "free" | "basic" | "standard" | "pro";
        /**
         * @description This enum is not backed by a particular database table.
         *     It's used in APIs and Jobs to agree upon ComfyUI style transfer style configurations.
         *
         *     DO NOT CHANGE VALUES WITHOUT A MIGRATION STRATEGY.
         * @enum {string}
         */
        StyleTransferName: "anime_2_5d" | "anime_2d_flat" | "cartoon_3d" | "comic_book" | "anime_ghibli" | "ink_punk" | "ink_splash" | "ink_bw_style" | "jojo_style" | "paper_origami" | "pixel_art" | "pop_art" | "realistic_1" | "realistic_2" | "anime_retro_neon" | "anime_standard" | "hr_giger" | "simpsons" | "carnage" | "pastel_cute_anime" | "bloom_lighting" | "25d_horror" | "creepy" | "creepy_vhs" | "trail_cam_footage" | "old_black_white_movie" | "horror_noir_black_white" | "techno_noir_black_white" | "black_white_20s" | "cyberpunk_anime" | "dragonball" | "realistic_matrix" | "realistic_cyberpunk" | "dreamer";
        SubscriptionInfo: {
            /** @description Namespace for the subscription. */
            namespace: components["schemas"]["PaymentsNamespace"];
            /**
             * Format: date-time
             * @description If the subscription is currently active, this is the next billing date.
             */
            next_bill_at?: string | null;
            /** @description Local key for the subscription. */
            product_slug: string;
            /**
             * Format: date-time
             * @description If the subscription is set to cancel, this is the end date of the subscription.
             */
            subscription_end_at?: string | null;
            /** @description Unique token for the subscription. */
            subscription_token: components["schemas"]["UserSubscriptionToken"];
        };
        UserDefaultAvatarInfo: {
            /** Format: int32 */
            color_index: number;
            /** Format: int32 */
            image_index: number;
        };
        /** @description Everything we need to refer to a user on the public web interface. */
        UserDetailsLight: {
            /** @description For users without a gravatar, we show one of our own avatars. */
            default_avatar: components["schemas"]["UserDefaultAvatarInfo"];
            /**
             * @description As of 2023-08-23, this is the username with capitalization
             *     (In the future, a display name can be customized by the user.)
             */
            display_name: string;
            /**
             * @description Email hash for Gravatar
             *     Always set for now since login is email/username+password.
             *     In the future this will need to become an optional *OR* be filled with a bogus hash.
             */
            gravatar_hash: string;
            /** @description The token for the user */
            user_token: components["schemas"]["UserToken"];
            /**
             * @description The unique username someone logs in with
             *     As of 2023-08-23, this is always lowercase
             */
            username: string;
        };
        /**
         * @description Used in the `users` table in a `VARCHAR` field (stored as comma separated set).
         *
         *     DO NOT CHANGE VALUES WITHOUT A MIGRATION STRATEGY.
         * @enum {string}
         */
        UserFeatureFlag: "explore_media" | "studio" | "upload_3d" | "video_style_transfer" | "sd_wl" | "hh" | "hh_rl" | "referrals" | "api_key" | "minimax" | "minimax_p";
        /** @description Primary key for the `user_subscriptions` table. */
        UserSubscriptionToken: string;
        /** @description The primary key for users. */
        UserToken: string;
        VideoPreviews: {
            /**
             * Format: uri
             * @description An animated gif preview of the video.
             */
            animated: string;
            /**
             * @description A template used to construct the animated thumbnail URL.
             *     Replace the string `{WIDTH}` with the desired width.
             */
            animated_thumbnail_template: string;
            /**
             * Format: uri
             * @description A static single frame preview image of the video.
             */
            still: string;
            /**
             * @description A template used to construct the still thumbnail URL.
             *     Replace the string `{WIDTH}` with the desired width.
             */
            still_thumbnail_template: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    google_sso_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleCreateAccountRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleCreateAccountSuccessResponse"];
                };
            };
            /** @description Bad input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommonWebError"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommonWebError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommonWebError"];
                };
            };
        };
    };
    get_session_credits_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: components["schemas"]["PaymentsNamespace"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionCreditsResponse"];
                };
            };
        };
    };
    batch_get_inference_job_status_handler: {
        parameters: {
            query: {
                /**
                 * @description A grab bag of tokens of various types.
                 *     Technically we should pair with token types, as that's the unique index.
                 *     But since each token family generally has its own prefix, this should be fine.
                 *
                 *     NB: We're using actix_web_lab's Query<T>, because the default actix_web Query<T> doesn't support URL
                 *     decoding sequences yet.
                 *     See https://github.com/actix/actix-web/issues/1301
                 */
                tokens: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchGetInferenceJobStatusSuccessResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_inference_job_status_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["schemas"]["InferenceJobToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInferenceJobStatusSuccessResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_session_jobs_handler: {
        parameters: {
            query?: {
                /** @description The opposite of include_states, this filters out states from view. */
                exclude_states?: string | null;
                /**
                 * @description NB: This can be one (or more comma-separated values) from `JobStatusPlus`.
                 *     ?include_states=pending or ?include_states=pending,started,complete_success (etc.)
                 */
                include_states?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSessionJobsSuccessResponse"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginSuccessResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginErrorResponse"];
                };
            };
        };
    };
    logout_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutSuccessResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommonWebError"];
                };
            };
        };
    };
    omni_gen_audio_cost_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OmniGenAudioCostAndGenerateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenAudioCostResponse"];
                };
            };
            /** @description Bad input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_image_cost_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OmniGenImageCostAndGenerateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenImageCostResponse"];
                };
            };
            /** @description Bad input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_mesh_cost_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OmniGenMeshCostAndGenerateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenMeshCostResponse"];
                };
            };
            /** @description Bad input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_splat_cost_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OmniGenSplatCostAndGenerateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenSplatCostResponse"];
                };
            };
            /** @description Bad input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_video_cost_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OmniGenVideoCostAndGenerateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenVideoCostResponse"];
                };
            };
            /** @description Bad input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_audio_models_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenAudioModelsResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_image_models_handler: {
        parameters: {
            query?: {
                /** @description Which provider's models to list. Defaults to "artcraft" if absent. */
                provider?: null | components["schemas"]["OmniGenImageModelsProvider"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenImageModelsResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_mesh_models_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenMeshModelsResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_splat_models_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenSplatModelsResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    omni_gen_video_models_handler: {
        parameters: {
            query?: {
                /** @description Which provider's models to list. Defaults to "artcraft" if absent. */
                provider?: null | components["schemas"]["OmniGenVideoModelsProvider"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmniGenVideoModelsResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_info_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfoSuccessResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_session_subscription_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: components["schemas"]["PaymentsNamespace"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSessionSubscriptionResponse"];
                };
            };
        };
    };
}
