
// NOTE: These are defined in Rust (as the source of truth) and duplicated in the frontend.
// In the future, we should use code gen (protobufs or similar) to keep the two sides in sync.

export enum CommonVideoModel {
  GrokVideo = "grok_video",
  GrokImagineVideo = "grok_imagine_video",
  GrokImagineVideo1p5 = "grok_imagine_video_1p5",
  Flux3 = "flux_3",
  Flux3Draft = "flux_3_draft",
  Kling16Pro = "kling_1p6_pro",
  Kling21Pro = "kling_2p1_pro",
  Kling21Master = "kling_2p1_master",
  Kling2p5TurboPro = "kling_2p5_turbo_pro",
  Kling2p6Pro = "kling_2p6_pro",
  Kling3p0Standard = "kling_3p0_standard",
  Kling3p0Pro = "kling_3p0_pro",
  HappyHorse1p0 = "happy_horse_1p0",
  Wan3p0 = "wan_3p0",
  Wan3p0Prime = "wan_3p0_prime",
  MinimaxH3 = "minimax_h3",
  MinimaxH3Turbo = "minimax_h3_turbo",
  MinimaxH3Ultra = "minimax_h3_ultra",
  Seedance10Lite = "seedance_1p0_lite",
  Seedance1p5Pro = "seedance_1p5_pro",
  Seedance2p0 = "seedance_2p0",
  Seedance2p0Fast = "seedance_2p0_fast",
  Seedance2p0BytePlus = "seedance_2p0_bp",
  Seedance2p0BytePlusFast = "seedance_2p0_bp_fast",
  Seedance2p0Ultra = "seedance_2p0_u",
  Seedance2p0UltraFast = "seedance_2p0_u_fast",
  Seedance2p0BytePlusUltra = "seedance_2p0_bpu",
  Seedance2p0BytePlusUltraFast = "seedance_2p0_bpu_fast",
  Seedance2p0Mini = "seedance_2p0_mini",
  Seedance2p0BytePlusMini = "seedance_2p0_bp_mini",
  Seedance2p0BytePlusUltraMini = "seedance_2p0_bpu_mini",
  Seedance2p5Preview = "seedance_2p5_preview",
  Seedance2p5 = "seedance_2p5",
  Seedance2p5Ultra = "seedance_2p5_u",
  Sora2 = "sora_2",
  Sora2Pro = "sora_2_pro",
  Veo2 = "veo_2",
  Veo3 = "veo_3",
  Veo3Fast = "veo_3_fast",
  Veo3p1 = "veo_3p1",
  Veo3p1Fast = "veo_3p1_fast",
  Veo3p1Lite = "veo_3p1_lite",
  ViduQ3 = "vidu_q3",
  ViduQ3Turbo = "vidu_q3_turbo",
  PreviewModel = "preview_model",
  PreviewModelFast = "preview_model_fast",
}
