pub mod plan_generate_image_fal_flux_1_dev;
pub mod plan_generate_image_fal_flux_1_schnell;
pub mod plan_generate_image_fal_nano_banana;
pub mod plan_generate_image_fal_nano_banana_2;
pub mod plan_generate_image_fal_nano_banana_pro;
