//! Parse OpenAI **Sora** (OpenAI Generative AI video) provenance out of an MP4.
//!
//! Like Veo, Sora attaches a [C2PA](https://c2pa.org/) Content Credentials
//! manifest (a JUMBF box with a CBOR claim) signed by OpenAI. The manifest's
//! `claim_generator` / signer identifies OpenAI; `digitalSourceType` is
//! `trainedAlgorithmicMedia`.
//!
//! ⚠️ **Unverified format.** Every Sora clip in our local sample set had been
//! re-encoded through ffmpeg (encoder `Lavf…`), which strips the C2PA box — so
//! this parser is modeled on OpenAI's documented Content Credentials structure
//! and the shared C2PA layout used by [`crate::veo_info`], but has **not** been
//! validated against an untouched Sora export. Field extraction is intentionally
//! generic (the C2PA markers we're confident about) until a clean sample exists.

use std::fs;
use std::path::Path;

use crate::error::VideoInfoError;
use crate::scan::{find, find_cert_serial, find_prefixed_uuid, text_after_key};

// ── Detection markers ──

/// OpenAI's signer / claim-generator identity in the C2PA manifest.
const OPENAI_MARKER: &[u8] = b"OpenAI";
/// A C2PA manifest must be present for these markers to be meaningful.
const C2PA_CLAIM_MARKER: &[u8] = b"c2pa.claim";
const JUMBF_MARKER: &[u8] = b"jumbf";
/// The Sora model token, when embedded.
const SORA_MARKER: &[u8] = b"sora";

/// Provenance extracted from an OpenAI Sora (OpenAI Generative AI) video.
#[derive(Debug, Clone, PartialEq)]
pub struct SoraInfo {
  /// Always `"OpenAI"` — the producer established by the C2PA signer / generator.
  pub producer: String,

  /// The model token if embedded (e.g. `"sora"`); often absent, like Veo.
  pub model_name: Option<String>,

  /// The `c2pa.created` action description, when present.
  pub created_description: Option<String>,

  /// IPTC digital source type URL — trained-algorithmic-media for these.
  pub digital_source_type: Option<String>,

  /// C2PA claim generator string.
  pub claim_generator: Option<String>,

  /// The manifest URN, e.g. `"urn:c2pa:…"`.
  pub manifest_id: Option<String>,

  /// The per-asset instance id.
  pub instance_id: Option<String>,

  /// Hex serial number of the leaf signing certificate.
  pub cert_serial: Option<String>,
}

impl SoraInfo {
  /// Parse Sora provenance from a video file on disk.
  pub fn from_path(path: impl AsRef<Path>) -> Result<SoraInfo, VideoInfoError> {
    let bytes = fs::read(path)?;
    Self::from_bytes(&bytes)
  }

  /// Parse Sora provenance from raw video bytes.
  ///
  /// Returns [`VideoInfoError::NotSora`] if no OpenAI C2PA manifest is present.
  pub fn from_bytes(data: &[u8]) -> Result<SoraInfo, VideoInfoError> {
    let has_c2pa = find(data, C2PA_CLAIM_MARKER).is_some() || find(data, JUMBF_MARKER).is_some();
    let is_openai = find(data, OPENAI_MARKER).is_some();
    if !(has_c2pa && is_openai) {
      return Err(VideoInfoError::NotSora);
    }

    Ok(SoraInfo {
      producer: "OpenAI".to_string(),
      model_name: find(data, SORA_MARKER).map(|_| "sora".to_string()),
      created_description: find_description_containing(data, b"OpenAI")
        .or_else(|| find_description_containing(data, b"Generated")),
      digital_source_type: text_after_key(data, b"digitalSourceType"),
      claim_generator: text_after_key(data, b"claim_generator"),
      manifest_id: find_prefixed_uuid(data, b"urn:c2pa:"),
      instance_id: text_after_key(data, b"instanceID"),
      cert_serial: find_cert_serial(data),
    })
  }
}

/// Find a CBOR `description` value whose text contains `needle`.
fn find_description_containing(data: &[u8], needle: &[u8]) -> Option<String> {
  let mut from = 0;
  while let Some(i) = crate::scan::find_from(data, b"description", from) {
    if let Some(text) = crate::scan::read_cbor_text(data, i + b"description".len()) {
      if text.as_bytes().windows(needle.len()).any(|w| w == needle) {
        return Some(text);
      }
    }
    from = i + b"description".len();
  }
  None
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::scan::push_cbor_text as push_text;

  fn synth_sora() -> Vec<u8> {
    let mut v = Vec::new();
    v.extend_from_slice(b"....ftypisom....moov....jumbfc2pa.claim");
    v.extend_from_slice(&[0xA0, 0x03, 0x02, 0x01, 0x02, 0x02, 0x03, 0xAB, 0xCD, 0xEF]);
    v.extend_from_slice(b"OpenAI, OPC LLC");
    v.extend_from_slice(b"urn:c2pa:11111111-2222-3333-4444-555555555555");
    v.extend_from_slice(b"c2pa.createdkdescription");
    push_text(&mut v, "Generated by OpenAI.");
    v.extend_from_slice(b"qdigitalSourceType");
    push_text(&mut v, "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia");
    v.extend_from_slice(b"jinstanceID");
    push_text(&mut v, "abcd1234-0000-0000-0000-000000000000");
    v.extend_from_slice(b"sora");
    v
  }

  #[test]
  fn parses_sora_manifest() {
    let info = SoraInfo::from_bytes(&synth_sora()).expect("should parse");
    assert_eq!(info.producer, "OpenAI");
    assert_eq!(info.model_name.as_deref(), Some("sora"));
    assert_eq!(info.created_description.as_deref(), Some("Generated by OpenAI."));
    assert_eq!(info.manifest_id.as_deref(), Some("urn:c2pa:11111111-2222-3333-4444-555555555555"));
    assert_eq!(info.instance_id.as_deref(), Some("abcd1234-0000-0000-0000-000000000000"));
    assert_eq!(info.cert_serial.as_deref(), Some("ABCDEF"));
    assert!(info.digital_source_type.as_deref().unwrap().contains("trainedAlgorithmicMedia"));
  }

  #[test]
  fn non_openai_returns_not_sora() {
    let data = b"....ftypisom....jumbfc2pa.claim....Volcengine_Ark_CN....";
    assert!(matches!(SoraInfo::from_bytes(data), Err(VideoInfoError::NotSora)));
  }

  #[test]
  fn openai_without_c2pa_returns_not_sora() {
    let data = b"....ftypisom....mentions OpenAI but no manifest....";
    assert!(matches!(SoraInfo::from_bytes(data), Err(VideoInfoError::NotSora)));
  }
}
