use crate::api::requests::videos::video_extension::video_extension::VideoExtensionRequest;
use crate::api::requests::videos::video_generation::cost::{
  output_mills_per_second,
  INPUT_MILLS_PER_SECOND_OF_SOURCE_VIDEO,
};
use crate::api::traits::grok_request_cost_calculator_trait::{GrokRequestCostCalculator, UsdMills};
use crate::api::traits::grok_request_source_duration_cost_calculator_trait::GrokRequestSourceDurationCostCalculator;
use crate::api::types::video_types::video_resolution::VideoResolution;

// `video_extension` charges:
//
//   Output: $0.07/sec × extension_duration   (70 mills/sec, since output
//           inherits the source's resolution capped at 720p)
//   Input:  $0.01/sec × source_duration      (10 mills/sec, UNKNOWN to us)
//
// `extension_duration` is the `duration` field on the request (xAI default
// is 6 seconds; range 1–10). `source_duration` is NOT in the request.
//
// Our `calculate_cost_in_mills` therefore returns ONLY the output portion.
// Callers who know the source duration should add:
//
//   source_duration_seconds * INPUT_MILLS_PER_SECOND_OF_SOURCE_VIDEO
//
// to get the true total.

/// xAI default duration for video_extension when `duration` is omitted.
const DEFAULT_EXTENSION_DURATION_SECONDS: u32 = 6;

impl GrokRequestCostCalculator for VideoExtensionRequest {
  /// Estimates the **output** portion only. The input portion depends on the
  /// source video's duration, which isn't in the request; callers should
  /// add it separately if they need a true total.
  ///
  /// If you DO have the source duration, use
  /// [`GrokRequestSourceDurationCostCalculator::calculate_cost_in_mills_with_source_duration`]
  /// instead — that returns the true total.
  fn calculate_cost_in_mills(&self) -> UsdMills {
    let extension_duration = self.duration.unwrap_or(DEFAULT_EXTENSION_DURATION_SECONDS) as u64;

    // Output inherits source resolution capped at 720p. Use 720p — both the
    // worst case (most expensive) and the most common output for source
    // videos generated by /v1/videos/generations at 720p.
    output_mills_per_second(VideoResolution::SevenTwentyP) * extension_duration
  }
}

impl GrokRequestSourceDurationCostCalculator for VideoExtensionRequest {
  /// Full cost = output (extension portion, known from request) + input
  /// (source duration × 10 mills/sec).
  fn calculate_cost_in_mills_with_source_duration(&self, source_duration_seconds: u32) -> UsdMills {
    let output_mills = self.calculate_cost_in_mills();
    let input_mills = INPUT_MILLS_PER_SECOND_OF_SOURCE_VIDEO * source_duration_seconds as u64;
    output_mills + input_mills
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::api::requests::videos::video_extension::video_extension::{
    VideoExtensionRequest, VideoExtensionSource,
  };
  use crate::api::types::video_types::video_model::VideoModel;

  fn make_request(
    duration: Option<u32>,
    source: VideoExtensionSource,
    model: Option<VideoModel>,
  ) -> VideoExtensionRequest {
    VideoExtensionRequest {
      prompt: "test".to_string(),
      source_video: source,
      model,
      duration,
    }
  }

  fn url_source() -> VideoExtensionSource {
    VideoExtensionSource::Url("https://example.com/v.mp4".to_string())
  }

  // ── Output portion (the part we CAN compute) ──

  mod output_portion {
    use super::*;

    #[test]
    fn default_duration_is_6_seconds() {
      // 70 × 6 = 420 mills = 42¢
      let req = make_request(None, url_source(), None);
      assert_eq!(req.calculate_cost_in_mills(), 420);
      assert_eq!(req.calculate_cost_in_cents(), 42);
    }

    #[test]
    fn one_second_extension() {
      // 70 × 1 = 70 mills = 7¢
      let req = make_request(Some(1), url_source(), None);
      assert_eq!(req.calculate_cost_in_mills(), 70);
      assert_eq!(req.calculate_cost_in_cents(), 7);
    }

    #[test]
    fn five_second_extension() {
      // 70 × 5 = 350 mills = 35¢
      let req = make_request(Some(5), url_source(), None);
      assert_eq!(req.calculate_cost_in_mills(), 350);
      assert_eq!(req.calculate_cost_in_cents(), 35);
    }

    #[test]
    fn ten_second_extension_is_max() {
      // 70 × 10 = 700 mills = 70¢
      let req = make_request(Some(10), url_source(), None);
      assert_eq!(req.calculate_cost_in_mills(), 700);
      assert_eq!(req.calculate_cost_in_cents(), 70);
    }
  }

  // ── Scaling ──

  mod scaling {
    use super::*;

    #[test]
    fn duration_scales_linearly() {
      for d in 1u32..=10 {
        let req = make_request(Some(d), url_source(), None);
        assert_eq!(req.calculate_cost_in_mills(), 70 * d as u64, "d={d}");
      }
    }
  }

  // ── Independence from non-pricing fields ──

  mod independence {
    use super::*;

    #[test]
    fn cost_is_independent_of_source_kind() {
      let url = make_request(Some(5), VideoExtensionSource::Url("u".to_string()), None);
      let file = make_request(Some(5), VideoExtensionSource::FileId("f".to_string()), None);
      assert_eq!(url.calculate_cost_in_mills(), file.calculate_cost_in_mills());
    }

    #[test]
    fn cost_is_independent_of_model_variant() {
      let mut base = make_request(Some(5), url_source(), None);
      let base_cost = base.calculate_cost_in_mills();
      base.model = Some(VideoModel::GrokImagineVideo);
      assert_eq!(base.calculate_cost_in_mills(), base_cost);
      base.model = Some(VideoModel::Custom("future".to_string()));
      assert_eq!(base.calculate_cost_in_mills(), base_cost);
    }

    #[test]
    fn cost_is_independent_of_prompt_length() {
      let mut base = make_request(Some(5), url_source(), None);
      let base_cost = base.calculate_cost_in_mills();
      base.prompt = "a much longer prompt with many more words to influence pricing... or not".to_string();
      assert_eq!(base.calculate_cost_in_mills(), base_cost);
    }
  }

  // ── Source-duration-aware variant ──

  mod with_source_duration {
    use super::*;

    #[test]
    fn five_extension_ten_source() {
      // output: 70 × 5 = 350 mills; input: 10 × 10 = 100 mills; total: 450
      let req = make_request(Some(5), url_source(), None);
      assert_eq!(req.calculate_cost_in_mills_with_source_duration(10), 450);
      assert_eq!(req.calculate_cost_in_cents_with_source_duration(10), 45);
    }

    #[test]
    fn default_extension_5_source() {
      // default ext=6s: output 70 × 6 = 420; input 10 × 5 = 50; total 470
      let req = make_request(None, url_source(), None);
      assert_eq!(req.calculate_cost_in_mills_with_source_duration(5), 470);
      assert_eq!(req.calculate_cost_in_cents_with_source_duration(5), 47);
    }

    #[test]
    fn ten_extension_zero_source() {
      // output 70 × 10 = 700; input 10 × 0 = 0; total 700
      let req = make_request(Some(10), url_source(), None);
      assert_eq!(req.calculate_cost_in_mills_with_source_duration(0), 700);
    }

    #[test]
    fn source_duration_scales_linearly() {
      let req = make_request(Some(5), url_source(), None); // output = 350
      for secs in 0u32..=30 {
        let expected = 350 + 10 * secs as u64;
        assert_eq!(req.calculate_cost_in_mills_with_source_duration(secs), expected, "secs={secs}");
      }
    }

    #[test]
    fn extension_duration_scales_linearly() {
      // Fix source at 10s (input portion = 100 mills).
      for ext in 1u32..=10 {
        let req = make_request(Some(ext), url_source(), None);
        let expected = 70 * ext as u64 + 100;
        assert_eq!(req.calculate_cost_in_mills_with_source_duration(10), expected, "ext={ext}");
      }
    }

    #[test]
    fn full_method_equals_output_only_plus_input() {
      // The source-duration variant should always equal the base + input portion.
      let req = make_request(Some(7), url_source(), None);
      let base = req.calculate_cost_in_mills();
      for secs in 0u32..=20 {
        let full = req.calculate_cost_in_mills_with_source_duration(secs);
        assert_eq!(full, base + 10 * secs as u64, "secs={secs}");
      }
    }

    #[test]
    fn cents_is_ceil_of_mills_over_ten() {
      // 75 mills (ext=1s, source=1/2s rounding edge case)
      // Make sure ceiling division behaves right.
      let req = make_request(Some(1), url_source(), None); // output = 70 mills
      // input 10 × 1 = 10; total = 80 mills = 8¢
      assert_eq!(req.calculate_cost_in_mills_with_source_duration(1), 80);
      assert_eq!(req.calculate_cost_in_cents_with_source_duration(1), 8);
    }
  }
}
